apiVersion: database.oci.m.upbound.io/v1alpha1
kind: ToolsRuntimeDatabaseToolsConnectionCredential
metadata:
  annotations:
    meta.upbound.io/example-id: database/v1alpha1/toolsruntimedatabasetoolsconnectioncredential
  labels:
    testing.upbound.io/example-name: test_database_tools_connection_credential
  name: test-database-tools-connection-credential
  namespace: upbound-system
spec:
  forProvider:
    databaseToolsConnectionIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_database_tools_connection
    key: ${var.database_tools_connection_credential_key}
    passwordSecretRef:
      key: example-key
      name: example-secret
    type: ${var.database_tools_connection_credential_type}
    userNameSelector:
      matchLabels:
        testing.upbound.io/example-name: test_user
