apiVersion: database.oci.m.upbound.io/v1alpha1
kind: ToolsRuntimeDatabaseToolsConnectionCredentialExecuteGrantee
metadata:
  annotations:
    meta.upbound.io/example-id: database/v1alpha1/toolsruntimedatabasetoolsconnectioncredentialexecutegrantee
  labels:
    testing.upbound.io/example-name: test_database_tools_connection_credential_execute_grantee
  name: test-database-tools-connection-credential-execute-grantee
  namespace: upbound-system
spec:
  forProvider:
    credentialKey: ${var.database_tools_connection_credential_execute_grantee_credential_key}
    databaseToolsConnectionIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_database_tools_connection
    key: ${var.database_tools_connection_credential_execute_grantee_key}
