apiVersion: database.oci.m.upbound.io/v1alpha1
kind: ToolsRuntimeDatabaseToolsConnectionCredentialPublicSynonym
metadata:
  annotations:
    meta.upbound.io/example-id: database/v1alpha1/toolsruntimedatabasetoolsconnectioncredentialpublicsynonym
  labels:
    testing.upbound.io/example-name: test_database_tools_connection_credential_public_synonym
  name: test-database-tools-connection-credential-public-synonym
  namespace: upbound-system
spec:
  forProvider:
    credentialKey: ${var.database_tools_connection_credential_public_synonym_credential_key}
    databaseToolsConnectionIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_database_tools_connection
    key: ${var.database_tools_connection_credential_public_synonym_key}
