/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type BdsClusterAdminPasswordResetActionInitParameters struct {
	BdsInstanceID *string `json:"bdsInstanceId,omitempty" tf:"bds_instance_id,omitempty"`

	CurrentClusterAdminPasswordSecretRef *v1.LocalSecretKeySelector `json:"currentClusterAdminPasswordSecretRef,omitempty" tf:"-"`

	ResetTrigger *string `json:"resetTrigger,omitempty" tf:"reset_trigger,omitempty"`

	SecretID *string `json:"secretId,omitempty" tf:"secret_id,omitempty"`

	Service *string `json:"service,omitempty" tf:"service,omitempty"`
}

type BdsClusterAdminPasswordResetActionObservation struct {
	BdsInstanceID *string `json:"bdsInstanceId,omitempty" tf:"bds_instance_id,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	ResetTrigger *string `json:"resetTrigger,omitempty" tf:"reset_trigger,omitempty"`

	SecretID *string `json:"secretId,omitempty" tf:"secret_id,omitempty"`

	Service *string `json:"service,omitempty" tf:"service,omitempty"`
}

type BdsClusterAdminPasswordResetActionParameters struct {

	// +kubebuilder:validation:Optional
	BdsInstanceID *string `json:"bdsInstanceId,omitempty" tf:"bds_instance_id,omitempty"`

	// +kubebuilder:validation:Optional
	CurrentClusterAdminPasswordSecretRef *v1.LocalSecretKeySelector `json:"currentClusterAdminPasswordSecretRef,omitempty" tf:"-"`

	// +kubebuilder:validation:Optional
	ResetTrigger *string `json:"resetTrigger,omitempty" tf:"reset_trigger,omitempty"`

	// +kubebuilder:validation:Optional
	SecretID *string `json:"secretId,omitempty" tf:"secret_id,omitempty"`

	// +kubebuilder:validation:Optional
	Service *string `json:"service,omitempty" tf:"service,omitempty"`
}

// BdsClusterAdminPasswordResetActionSpec defines the desired state of BdsClusterAdminPasswordResetAction
type BdsClusterAdminPasswordResetActionSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            BdsClusterAdminPasswordResetActionParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider BdsClusterAdminPasswordResetActionInitParameters `json:"initProvider,omitempty"`
}

// BdsClusterAdminPasswordResetActionStatus defines the observed state of BdsClusterAdminPasswordResetAction.
type BdsClusterAdminPasswordResetActionStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        BdsClusterAdminPasswordResetActionObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// BdsClusterAdminPasswordResetAction is the Schema for the BdsClusterAdminPasswordResetActions API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,oci}
type BdsClusterAdminPasswordResetAction struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.bdsInstanceId) || (has(self.initProvider) && has(self.initProvider.bdsInstanceId))",message="spec.forProvider.bdsInstanceId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.service) || (has(self.initProvider) && has(self.initProvider.service))",message="spec.forProvider.service is a required parameter"
	Spec   BdsClusterAdminPasswordResetActionSpec   `json:"spec"`
	Status BdsClusterAdminPasswordResetActionStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// BdsClusterAdminPasswordResetActionList contains a list of BdsClusterAdminPasswordResetActions
type BdsClusterAdminPasswordResetActionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []BdsClusterAdminPasswordResetAction `json:"items"`
}

// Repository type metadata.
var (
	BdsClusterAdminPasswordResetAction_Kind             = "BdsClusterAdminPasswordResetAction"
	BdsClusterAdminPasswordResetAction_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: BdsClusterAdminPasswordResetAction_Kind}.String()
	BdsClusterAdminPasswordResetAction_KindAPIVersion   = BdsClusterAdminPasswordResetAction_Kind + "." + CRDGroupVersion.String()
	BdsClusterAdminPasswordResetAction_GroupVersionKind = CRDGroupVersion.WithKind(BdsClusterAdminPasswordResetAction_Kind)
)

func init() {
	SchemeBuilder.Register(&BdsClusterAdminPasswordResetAction{}, &BdsClusterAdminPasswordResetActionList{})
}
