/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type BdsInstanceReplaceNodeActionInitParameters struct {

	// The OCID of the Big Data Service cluster.
	BdsInstanceID *string `json:"bdsInstanceId,omitempty" tf:"bds_instance_id,omitempty"`

	// Base64-encoded cluster admin password. Use this or secret_id.
	ClusterAdminPasswordSecretRef *v1.LocalSecretKeySelector `json:"clusterAdminPasswordSecretRef,omitempty" tf:"-"`

	// The OCID of the node backup to use for replacement.
	NodeBackupID *string `json:"nodeBackupId,omitempty" tf:"node_backup_id,omitempty"`

	// Host name of the node to replace.
	NodeHostName *string `json:"nodeHostName,omitempty" tf:"node_host_name,omitempty"`

	// The OCID of the secret that stores the cluster admin password. Use this or cluster_admin_password.
	SecretID *string `json:"secretId,omitempty" tf:"secret_id,omitempty"`

	// The shape to use for the replacement node. If not specified, the existing node shape is used.
	Shape *string `json:"shape,omitempty" tf:"shape,omitempty"`
}

type BdsInstanceReplaceNodeActionObservation struct {

	// The OCID of the Big Data Service cluster.
	BdsInstanceID *string `json:"bdsInstanceId,omitempty" tf:"bds_instance_id,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The OCID of the node backup to use for replacement.
	NodeBackupID *string `json:"nodeBackupId,omitempty" tf:"node_backup_id,omitempty"`

	// Host name of the node to replace.
	NodeHostName *string `json:"nodeHostName,omitempty" tf:"node_host_name,omitempty"`

	// The OCID of the secret that stores the cluster admin password. Use this or cluster_admin_password.
	SecretID *string `json:"secretId,omitempty" tf:"secret_id,omitempty"`

	// The shape to use for the replacement node. If not specified, the existing node shape is used.
	Shape *string `json:"shape,omitempty" tf:"shape,omitempty"`
}

type BdsInstanceReplaceNodeActionParameters struct {

	// The OCID of the Big Data Service cluster.
	// +kubebuilder:validation:Optional
	BdsInstanceID *string `json:"bdsInstanceId,omitempty" tf:"bds_instance_id,omitempty"`

	// Base64-encoded cluster admin password. Use this or secret_id.
	// +kubebuilder:validation:Optional
	ClusterAdminPasswordSecretRef *v1.LocalSecretKeySelector `json:"clusterAdminPasswordSecretRef,omitempty" tf:"-"`

	// The OCID of the node backup to use for replacement.
	// +kubebuilder:validation:Optional
	NodeBackupID *string `json:"nodeBackupId,omitempty" tf:"node_backup_id,omitempty"`

	// Host name of the node to replace.
	// +kubebuilder:validation:Optional
	NodeHostName *string `json:"nodeHostName,omitempty" tf:"node_host_name,omitempty"`

	// The OCID of the secret that stores the cluster admin password. Use this or cluster_admin_password.
	// +kubebuilder:validation:Optional
	SecretID *string `json:"secretId,omitempty" tf:"secret_id,omitempty"`

	// The shape to use for the replacement node. If not specified, the existing node shape is used.
	// +kubebuilder:validation:Optional
	Shape *string `json:"shape,omitempty" tf:"shape,omitempty"`
}

// BdsInstanceReplaceNodeActionSpec defines the desired state of BdsInstanceReplaceNodeAction
type BdsInstanceReplaceNodeActionSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            BdsInstanceReplaceNodeActionParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider BdsInstanceReplaceNodeActionInitParameters `json:"initProvider,omitempty"`
}

// BdsInstanceReplaceNodeActionStatus defines the observed state of BdsInstanceReplaceNodeAction.
type BdsInstanceReplaceNodeActionStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        BdsInstanceReplaceNodeActionObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// BdsInstanceReplaceNodeAction is the Schema for the BdsInstanceReplaceNodeActions API. Provides the Bds Instance Replace Node Action resource in Oracle Cloud Infrastructure Big Data Service service
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,oci}
type BdsInstanceReplaceNodeAction struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.bdsInstanceId) || (has(self.initProvider) && has(self.initProvider.bdsInstanceId))",message="spec.forProvider.bdsInstanceId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.nodeHostName) || (has(self.initProvider) && has(self.initProvider.nodeHostName))",message="spec.forProvider.nodeHostName is a required parameter"
	Spec   BdsInstanceReplaceNodeActionSpec   `json:"spec"`
	Status BdsInstanceReplaceNodeActionStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// BdsInstanceReplaceNodeActionList contains a list of BdsInstanceReplaceNodeActions
type BdsInstanceReplaceNodeActionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []BdsInstanceReplaceNodeAction `json:"items"`
}

// Repository type metadata.
var (
	BdsInstanceReplaceNodeAction_Kind             = "BdsInstanceReplaceNodeAction"
	BdsInstanceReplaceNodeAction_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: BdsInstanceReplaceNodeAction_Kind}.String()
	BdsInstanceReplaceNodeAction_KindAPIVersion   = BdsInstanceReplaceNodeAction_Kind + "." + CRDGroupVersion.String()
	BdsInstanceReplaceNodeAction_GroupVersionKind = CRDGroupVersion.WithKind(BdsInstanceReplaceNodeAction_Kind)
)

func init() {
	SchemeBuilder.Register(&BdsInstanceReplaceNodeAction{}, &BdsInstanceReplaceNodeActionList{})
}
