/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type ToolsRuntimeDatabaseToolsConnectionCredentialPublicSynonymInitParameters struct {

	// The name of the credential
	CredentialKey *string `json:"credentialKey,omitempty" tf:"credential_key,omitempty"`

	// The OCID of a Database Tools connection.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/cluster/database/v1alpha1.ToolsDatabaseToolsConnection
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	DatabaseToolsConnectionID *string `json:"databaseToolsConnectionId,omitempty" tf:"database_tools_connection_id,omitempty"`

	// Reference to a ToolsDatabaseToolsConnection in database to populate databaseToolsConnectionId.
	// +kubebuilder:validation:Optional
	DatabaseToolsConnectionIDRef *v1.Reference `json:"databaseToolsConnectionIdRef,omitempty" tf:"-"`

	// Selector for a ToolsDatabaseToolsConnection in database to populate databaseToolsConnectionId.
	// +kubebuilder:validation:Optional
	DatabaseToolsConnectionIDSelector *v1.Selector `json:"databaseToolsConnectionIdSelector,omitempty" tf:"-"`

	// The name of the public synonym for the credential
	Key *string `json:"key,omitempty" tf:"key,omitempty"`
}

type ToolsRuntimeDatabaseToolsConnectionCredentialPublicSynonymObservation struct {

	// The name of the credential
	CredentialKey *string `json:"credentialKey,omitempty" tf:"credential_key,omitempty"`

	// The OCID of a Database Tools connection.
	DatabaseToolsConnectionID *string `json:"databaseToolsConnectionId,omitempty" tf:"database_tools_connection_id,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The name of the public synonym for the credential
	Key *string `json:"key,omitempty" tf:"key,omitempty"`
}

type ToolsRuntimeDatabaseToolsConnectionCredentialPublicSynonymParameters struct {

	// The name of the credential
	// +kubebuilder:validation:Optional
	CredentialKey *string `json:"credentialKey,omitempty" tf:"credential_key,omitempty"`

	// The OCID of a Database Tools connection.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/cluster/database/v1alpha1.ToolsDatabaseToolsConnection
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	DatabaseToolsConnectionID *string `json:"databaseToolsConnectionId,omitempty" tf:"database_tools_connection_id,omitempty"`

	// Reference to a ToolsDatabaseToolsConnection in database to populate databaseToolsConnectionId.
	// +kubebuilder:validation:Optional
	DatabaseToolsConnectionIDRef *v1.Reference `json:"databaseToolsConnectionIdRef,omitempty" tf:"-"`

	// Selector for a ToolsDatabaseToolsConnection in database to populate databaseToolsConnectionId.
	// +kubebuilder:validation:Optional
	DatabaseToolsConnectionIDSelector *v1.Selector `json:"databaseToolsConnectionIdSelector,omitempty" tf:"-"`

	// The name of the public synonym for the credential
	// +kubebuilder:validation:Optional
	Key *string `json:"key,omitempty" tf:"key,omitempty"`
}

// ToolsRuntimeDatabaseToolsConnectionCredentialPublicSynonymSpec defines the desired state of ToolsRuntimeDatabaseToolsConnectionCredentialPublicSynonym
type ToolsRuntimeDatabaseToolsConnectionCredentialPublicSynonymSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ToolsRuntimeDatabaseToolsConnectionCredentialPublicSynonymParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ToolsRuntimeDatabaseToolsConnectionCredentialPublicSynonymInitParameters `json:"initProvider,omitempty"`
}

// ToolsRuntimeDatabaseToolsConnectionCredentialPublicSynonymStatus defines the observed state of ToolsRuntimeDatabaseToolsConnectionCredentialPublicSynonym.
type ToolsRuntimeDatabaseToolsConnectionCredentialPublicSynonymStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ToolsRuntimeDatabaseToolsConnectionCredentialPublicSynonymObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ToolsRuntimeDatabaseToolsConnectionCredentialPublicSynonym is the Schema for the ToolsRuntimeDatabaseToolsConnectionCredentialPublicSynonyms API. Provides the Database Tools Connection Credential Public Synonym resource in Oracle Cloud Infrastructure Database Tools Runtime service
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,oci}
type ToolsRuntimeDatabaseToolsConnectionCredentialPublicSynonym struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.credentialKey) || (has(self.initProvider) && has(self.initProvider.credentialKey))",message="spec.forProvider.credentialKey is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.key) || (has(self.initProvider) && has(self.initProvider.key))",message="spec.forProvider.key is a required parameter"
	Spec   ToolsRuntimeDatabaseToolsConnectionCredentialPublicSynonymSpec   `json:"spec"`
	Status ToolsRuntimeDatabaseToolsConnectionCredentialPublicSynonymStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ToolsRuntimeDatabaseToolsConnectionCredentialPublicSynonymList contains a list of ToolsRuntimeDatabaseToolsConnectionCredentialPublicSynonyms
type ToolsRuntimeDatabaseToolsConnectionCredentialPublicSynonymList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ToolsRuntimeDatabaseToolsConnectionCredentialPublicSynonym `json:"items"`
}

// Repository type metadata.
var (
	ToolsRuntimeDatabaseToolsConnectionCredentialPublicSynonym_Kind             = "ToolsRuntimeDatabaseToolsConnectionCredentialPublicSynonym"
	ToolsRuntimeDatabaseToolsConnectionCredentialPublicSynonym_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ToolsRuntimeDatabaseToolsConnectionCredentialPublicSynonym_Kind}.String()
	ToolsRuntimeDatabaseToolsConnectionCredentialPublicSynonym_KindAPIVersion   = ToolsRuntimeDatabaseToolsConnectionCredentialPublicSynonym_Kind + "." + CRDGroupVersion.String()
	ToolsRuntimeDatabaseToolsConnectionCredentialPublicSynonym_GroupVersionKind = CRDGroupVersion.WithKind(ToolsRuntimeDatabaseToolsConnectionCredentialPublicSynonym_Kind)
)

func init() {
	SchemeBuilder.Register(&ToolsRuntimeDatabaseToolsConnectionCredentialPublicSynonym{}, &ToolsRuntimeDatabaseToolsConnectionCredentialPublicSynonymList{})
}
