/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type ToolsRuntimeDatabaseToolsConnectionCredentialInitParameters struct {

	// The OCID of a Database Tools connection.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/cluster/database/v1alpha1.ToolsDatabaseToolsConnection
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	DatabaseToolsConnectionID *string `json:"databaseToolsConnectionId,omitempty" tf:"database_tools_connection_id,omitempty"`

	// Reference to a ToolsDatabaseToolsConnection in database to populate databaseToolsConnectionId.
	// +kubebuilder:validation:Optional
	DatabaseToolsConnectionIDRef *v1.Reference `json:"databaseToolsConnectionIdRef,omitempty" tf:"-"`

	// Selector for a ToolsDatabaseToolsConnection in database to populate databaseToolsConnectionId.
	// +kubebuilder:validation:Optional
	DatabaseToolsConnectionIDSelector *v1.Selector `json:"databaseToolsConnectionIdSelector,omitempty" tf:"-"`

	// The credential_name to be created
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// (Updatable) The password for the new credential.
	PasswordSecretRef v1.SecretKeySelector `json:"passwordSecretRef" tf:"-"`

	// (Updatable) The type of credential.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (Updatable) The username for the new credential.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/cluster/identity/v1alpha1.User
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("name",false)
	UserName *string `json:"userName,omitempty" tf:"user_name,omitempty"`

	// Reference to a User in identity to populate userName.
	// +kubebuilder:validation:Optional
	UserNameRef *v1.Reference `json:"userNameRef,omitempty" tf:"-"`

	// Selector for a User in identity to populate userName.
	// +kubebuilder:validation:Optional
	UserNameSelector *v1.Selector `json:"userNameSelector,omitempty" tf:"-"`
}

type ToolsRuntimeDatabaseToolsConnectionCredentialObservation struct {

	// The OCID of a Database Tools connection.
	DatabaseToolsConnectionID *string `json:"databaseToolsConnectionId,omitempty" tf:"database_tools_connection_id,omitempty"`

	// Indicates whether this credential is enabled (TRUE) or not (FALSE)
	Enabled *string `json:"enabled,omitempty" tf:"enabled,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The credential_name to be created
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// Indicates whether this refers to a public synonym or not.
	KeyType *string `json:"keyType,omitempty" tf:"key_type,omitempty"`

	// Owner of the credential
	Owner *string `json:"owner,omitempty" tf:"owner,omitempty"`

	// A related resource for a credential.
	RelatedResource []ToolsRuntimeDatabaseToolsConnectionCredentialRelatedResourceObservation `json:"relatedResource,omitempty" tf:"related_resource,omitempty"`

	// (Updatable) The type of credential.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (Updatable) The username for the new credential.
	UserName *string `json:"userName,omitempty" tf:"user_name,omitempty"`

	// For a Windows target, the Windows domain to use when logging in
	WindowsDomain *string `json:"windowsDomain,omitempty" tf:"windows_domain,omitempty"`
}

type ToolsRuntimeDatabaseToolsConnectionCredentialParameters struct {

	// The OCID of a Database Tools connection.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/cluster/database/v1alpha1.ToolsDatabaseToolsConnection
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	DatabaseToolsConnectionID *string `json:"databaseToolsConnectionId,omitempty" tf:"database_tools_connection_id,omitempty"`

	// Reference to a ToolsDatabaseToolsConnection in database to populate databaseToolsConnectionId.
	// +kubebuilder:validation:Optional
	DatabaseToolsConnectionIDRef *v1.Reference `json:"databaseToolsConnectionIdRef,omitempty" tf:"-"`

	// Selector for a ToolsDatabaseToolsConnection in database to populate databaseToolsConnectionId.
	// +kubebuilder:validation:Optional
	DatabaseToolsConnectionIDSelector *v1.Selector `json:"databaseToolsConnectionIdSelector,omitempty" tf:"-"`

	// The credential_name to be created
	// +kubebuilder:validation:Optional
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// (Updatable) The password for the new credential.
	// +kubebuilder:validation:Optional
	PasswordSecretRef v1.SecretKeySelector `json:"passwordSecretRef" tf:"-"`

	// (Updatable) The type of credential.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (Updatable) The username for the new credential.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/cluster/identity/v1alpha1.User
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("name",false)
	// +kubebuilder:validation:Optional
	UserName *string `json:"userName,omitempty" tf:"user_name,omitempty"`

	// Reference to a User in identity to populate userName.
	// +kubebuilder:validation:Optional
	UserNameRef *v1.Reference `json:"userNameRef,omitempty" tf:"-"`

	// Selector for a User in identity to populate userName.
	// +kubebuilder:validation:Optional
	UserNameSelector *v1.Selector `json:"userNameSelector,omitempty" tf:"-"`
}

type ToolsRuntimeDatabaseToolsConnectionCredentialRelatedResourceInitParameters struct {
}

type ToolsRuntimeDatabaseToolsConnectionCredentialRelatedResourceObservation struct {

	// The OCID of the related resource.
	Identifier *string `json:"identifier,omitempty" tf:"identifier,omitempty"`

	// (Updatable) The type of credential.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ToolsRuntimeDatabaseToolsConnectionCredentialRelatedResourceParameters struct {
}

// ToolsRuntimeDatabaseToolsConnectionCredentialSpec defines the desired state of ToolsRuntimeDatabaseToolsConnectionCredential
type ToolsRuntimeDatabaseToolsConnectionCredentialSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ToolsRuntimeDatabaseToolsConnectionCredentialParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ToolsRuntimeDatabaseToolsConnectionCredentialInitParameters `json:"initProvider,omitempty"`
}

// ToolsRuntimeDatabaseToolsConnectionCredentialStatus defines the observed state of ToolsRuntimeDatabaseToolsConnectionCredential.
type ToolsRuntimeDatabaseToolsConnectionCredentialStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ToolsRuntimeDatabaseToolsConnectionCredentialObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ToolsRuntimeDatabaseToolsConnectionCredential is the Schema for the ToolsRuntimeDatabaseToolsConnectionCredentials API. Provides the Database Tools Connection Credential resource in Oracle Cloud Infrastructure Database Tools Runtime service
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,oci}
type ToolsRuntimeDatabaseToolsConnectionCredential struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.key) || (has(self.initProvider) && has(self.initProvider.key))",message="spec.forProvider.key is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.passwordSecretRef)",message="spec.forProvider.passwordSecretRef is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.type) || (has(self.initProvider) && has(self.initProvider.type))",message="spec.forProvider.type is a required parameter"
	Spec   ToolsRuntimeDatabaseToolsConnectionCredentialSpec   `json:"spec"`
	Status ToolsRuntimeDatabaseToolsConnectionCredentialStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ToolsRuntimeDatabaseToolsConnectionCredentialList contains a list of ToolsRuntimeDatabaseToolsConnectionCredentials
type ToolsRuntimeDatabaseToolsConnectionCredentialList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ToolsRuntimeDatabaseToolsConnectionCredential `json:"items"`
}

// Repository type metadata.
var (
	ToolsRuntimeDatabaseToolsConnectionCredential_Kind             = "ToolsRuntimeDatabaseToolsConnectionCredential"
	ToolsRuntimeDatabaseToolsConnectionCredential_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ToolsRuntimeDatabaseToolsConnectionCredential_Kind}.String()
	ToolsRuntimeDatabaseToolsConnectionCredential_KindAPIVersion   = ToolsRuntimeDatabaseToolsConnectionCredential_Kind + "." + CRDGroupVersion.String()
	ToolsRuntimeDatabaseToolsConnectionCredential_GroupVersionKind = CRDGroupVersion.WithKind(ToolsRuntimeDatabaseToolsConnectionCredential_Kind)
)

func init() {
	SchemeBuilder.Register(&ToolsRuntimeDatabaseToolsConnectionCredential{}, &ToolsRuntimeDatabaseToolsConnectionCredentialList{})
}
