/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ArchiveSourceDetailsInitParameters struct {

	// (Updatable) The base64-encoded archive file of the function code. The archive file must contain all the files for the function. Please refer to functions documentation for maximum allowed size and supported archive formats.
	ArchiveFile *string `json:"archiveFile,omitempty" tf:"archive_file,omitempty"`

	// (Updatable) Type of the Archive Source. Possible values: OBJECT_STORAGE_ARCHIVE and DIRECT_ARCHIVE.
	ArchiveSourceType *string `json:"archiveSourceType,omitempty" tf:"archive_source_type,omitempty"`

	// (Updatable) The name of the Object Storage bucket.
	Bucket *string `json:"bucket,omitempty" tf:"bucket,omitempty"`

	// (Updatable) The Object Storage namespace.
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// (Updatable) The name of the Object Storage object.
	Object *string `json:"object,omitempty" tf:"object,omitempty"`

	// (Applicable when archive_source_type=OBJECT_STORAGE_ARCHIVE) (Updatable) VersionId used to identify a particular version of the object. If not specified, the latest version of the object is used.
	ObjectVersionID *string `json:"objectVersionId,omitempty" tf:"object_version_id,omitempty"`
}

type ArchiveSourceDetailsObservation struct {

	// (Updatable) The base64-encoded archive file of the function code. The archive file must contain all the files for the function. Please refer to functions documentation for maximum allowed size and supported archive formats.
	ArchiveFile *string `json:"archiveFile,omitempty" tf:"archive_file,omitempty"`

	// (Updatable) Type of the Archive Source. Possible values: OBJECT_STORAGE_ARCHIVE and DIRECT_ARCHIVE.
	ArchiveSourceType *string `json:"archiveSourceType,omitempty" tf:"archive_source_type,omitempty"`

	// (Updatable) The name of the Object Storage bucket.
	Bucket *string `json:"bucket,omitempty" tf:"bucket,omitempty"`

	// (Updatable) The Object Storage namespace.
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// (Updatable) The name of the Object Storage object.
	Object *string `json:"object,omitempty" tf:"object,omitempty"`

	// (Applicable when archive_source_type=OBJECT_STORAGE_ARCHIVE) (Updatable) VersionId used to identify a particular version of the object. If not specified, the latest version of the object is used.
	ObjectVersionID *string `json:"objectVersionId,omitempty" tf:"object_version_id,omitempty"`
}

type ArchiveSourceDetailsParameters struct {

	// (Updatable) The base64-encoded archive file of the function code. The archive file must contain all the files for the function. Please refer to functions documentation for maximum allowed size and supported archive formats.
	// +kubebuilder:validation:Optional
	ArchiveFile *string `json:"archiveFile,omitempty" tf:"archive_file,omitempty"`

	// (Updatable) Type of the Archive Source. Possible values: OBJECT_STORAGE_ARCHIVE and DIRECT_ARCHIVE.
	// +kubebuilder:validation:Optional
	ArchiveSourceType *string `json:"archiveSourceType" tf:"archive_source_type,omitempty"`

	// (Updatable) The name of the Object Storage bucket.
	// +kubebuilder:validation:Optional
	Bucket *string `json:"bucket,omitempty" tf:"bucket,omitempty"`

	// (Updatable) The Object Storage namespace.
	// +kubebuilder:validation:Optional
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// (Updatable) The name of the Object Storage object.
	// +kubebuilder:validation:Optional
	Object *string `json:"object,omitempty" tf:"object,omitempty"`

	// (Applicable when archive_source_type=OBJECT_STORAGE_ARCHIVE) (Updatable) VersionId used to identify a particular version of the object. If not specified, the latest version of the object is used.
	// +kubebuilder:validation:Optional
	ObjectVersionID *string `json:"objectVersionId,omitempty" tf:"object_version_id,omitempty"`
}

type FailureDestinationInitParameters struct {

	// (Applicable when kind=QUEUE) (Updatable) The ID of the channel in the queue.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/mysql/v1alpha1.MysqlChannel
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	ChannelID *string `json:"channelId,omitempty" tf:"channel_id,omitempty"`

	// Reference to a MysqlChannel in mysql to populate channelId.
	// +kubebuilder:validation:Optional
	ChannelIDRef *v1.NamespacedReference `json:"channelIdRef,omitempty" tf:"-"`

	// Selector for a MysqlChannel in mysql to populate channelId.
	// +kubebuilder:validation:Optional
	ChannelIDSelector *v1.NamespacedSelector `json:"channelIdSelector,omitempty" tf:"-"`

	// (Updatable) The type of destination for the response to a failed detached function invocation.
	Kind *string `json:"kind,omitempty" tf:"kind,omitempty"`

	// (Updatable) The OCID of the queue.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/queue/v1alpha1.Queue
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	QueueID *string `json:"queueId,omitempty" tf:"queue_id,omitempty"`

	// Reference to a Queue in queue to populate queueId.
	// +kubebuilder:validation:Optional
	QueueIDRef *v1.NamespacedReference `json:"queueIdRef,omitempty" tf:"-"`

	// Selector for a Queue in queue to populate queueId.
	// +kubebuilder:validation:Optional
	QueueIDSelector *v1.NamespacedSelector `json:"queueIdSelector,omitempty" tf:"-"`

	// (Updatable) The OCID of the stream.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/streaming/v1alpha1.Stream
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	StreamID *string `json:"streamId,omitempty" tf:"stream_id,omitempty"`

	// Reference to a Stream in streaming to populate streamId.
	// +kubebuilder:validation:Optional
	StreamIDRef *v1.NamespacedReference `json:"streamIdRef,omitempty" tf:"-"`

	// Selector for a Stream in streaming to populate streamId.
	// +kubebuilder:validation:Optional
	StreamIDSelector *v1.NamespacedSelector `json:"streamIdSelector,omitempty" tf:"-"`

	// (Updatable) The OCID of the topic.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/ons/v1alpha1.NotificationTopic
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	TopicID *string `json:"topicId,omitempty" tf:"topic_id,omitempty"`

	// Reference to a NotificationTopic in ons to populate topicId.
	// +kubebuilder:validation:Optional
	TopicIDRef *v1.NamespacedReference `json:"topicIdRef,omitempty" tf:"-"`

	// Selector for a NotificationTopic in ons to populate topicId.
	// +kubebuilder:validation:Optional
	TopicIDSelector *v1.NamespacedSelector `json:"topicIdSelector,omitempty" tf:"-"`
}

type FailureDestinationObservation struct {

	// (Applicable when kind=QUEUE) (Updatable) The ID of the channel in the queue.
	ChannelID *string `json:"channelId,omitempty" tf:"channel_id,omitempty"`

	// (Updatable) The type of destination for the response to a failed detached function invocation.
	Kind *string `json:"kind,omitempty" tf:"kind,omitempty"`

	// (Updatable) The OCID of the queue.
	QueueID *string `json:"queueId,omitempty" tf:"queue_id,omitempty"`

	// (Updatable) The OCID of the stream.
	StreamID *string `json:"streamId,omitempty" tf:"stream_id,omitempty"`

	// (Updatable) The OCID of the topic.
	TopicID *string `json:"topicId,omitempty" tf:"topic_id,omitempty"`
}

type FailureDestinationParameters struct {

	// (Applicable when kind=QUEUE) (Updatable) The ID of the channel in the queue.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/mysql/v1alpha1.MysqlChannel
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	ChannelID *string `json:"channelId,omitempty" tf:"channel_id,omitempty"`

	// Reference to a MysqlChannel in mysql to populate channelId.
	// +kubebuilder:validation:Optional
	ChannelIDRef *v1.NamespacedReference `json:"channelIdRef,omitempty" tf:"-"`

	// Selector for a MysqlChannel in mysql to populate channelId.
	// +kubebuilder:validation:Optional
	ChannelIDSelector *v1.NamespacedSelector `json:"channelIdSelector,omitempty" tf:"-"`

	// (Updatable) The type of destination for the response to a failed detached function invocation.
	// +kubebuilder:validation:Optional
	Kind *string `json:"kind" tf:"kind,omitempty"`

	// (Updatable) The OCID of the queue.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/queue/v1alpha1.Queue
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	QueueID *string `json:"queueId,omitempty" tf:"queue_id,omitempty"`

	// Reference to a Queue in queue to populate queueId.
	// +kubebuilder:validation:Optional
	QueueIDRef *v1.NamespacedReference `json:"queueIdRef,omitempty" tf:"-"`

	// Selector for a Queue in queue to populate queueId.
	// +kubebuilder:validation:Optional
	QueueIDSelector *v1.NamespacedSelector `json:"queueIdSelector,omitempty" tf:"-"`

	// (Updatable) The OCID of the stream.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/streaming/v1alpha1.Stream
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	StreamID *string `json:"streamId,omitempty" tf:"stream_id,omitempty"`

	// Reference to a Stream in streaming to populate streamId.
	// +kubebuilder:validation:Optional
	StreamIDRef *v1.NamespacedReference `json:"streamIdRef,omitempty" tf:"-"`

	// Selector for a Stream in streaming to populate streamId.
	// +kubebuilder:validation:Optional
	StreamIDSelector *v1.NamespacedSelector `json:"streamIdSelector,omitempty" tf:"-"`

	// (Updatable) The OCID of the topic.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/ons/v1alpha1.NotificationTopic
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	TopicID *string `json:"topicId,omitempty" tf:"topic_id,omitempty"`

	// Reference to a NotificationTopic in ons to populate topicId.
	// +kubebuilder:validation:Optional
	TopicIDRef *v1.NamespacedReference `json:"topicIdRef,omitempty" tf:"-"`

	// Selector for a NotificationTopic in ons to populate topicId.
	// +kubebuilder:validation:Optional
	TopicIDSelector *v1.NamespacedSelector `json:"topicIdSelector,omitempty" tf:"-"`
}

type FunctionInitParameters struct {

	// The OCID of the application this function belongs to.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/functions/v1alpha1.Application
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	ApplicationID *string `json:"applicationId,omitempty" tf:"application_id,omitempty"`

	// Reference to a Application in functions to populate applicationId.
	// +kubebuilder:validation:Optional
	ApplicationIDRef *v1.NamespacedReference `json:"applicationIdRef,omitempty" tf:"-"`

	// Selector for a Application in functions to populate applicationId.
	// +kubebuilder:validation:Optional
	ApplicationIDSelector *v1.NamespacedSelector `json:"applicationIdSelector,omitempty" tf:"-"`

	// (Updatable) Function configuration. These values are passed on to the function as environment variables, this overrides application configuration values. Keys must be ASCII strings consisting solely of letters, digits, and the '_' (underscore) character, and must not begin with a digit. Values should be limited to printable unicode characters.  Example: {"MY_FUNCTION_CONFIG": "ConfVal"}
	// +mapType=granular
	Config map[string]*string `json:"config,omitempty" tf:"config,omitempty"`

	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see Resource Tags.  Example: {"Operations.CostCenter": "42"}
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// (Updatable) Timeout for detached function invocations. Value in seconds.
	DetachedModeTimeoutInSeconds *float64 `json:"detachedModeTimeoutInSeconds,omitempty" tf:"detached_mode_timeout_in_seconds,omitempty"`

	// The display name of the function. The display name must be unique within the application containing the function. Avoid entering confidential information.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Updatable) An object that represents the destination to which Oracle Functions will send an invocation record with the details of the error of the failed detached function invocation. A notification is an example of a failure destination.  Example: {"kind": "NOTIFICATION", "topicId": "topic_OCID"}
	FailureDestination []FailureDestinationInitParameters `json:"failureDestination,omitempty" tf:"failure_destination,omitempty"`

	// (Updatable) Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace. For more information, see Resource Tags.  Example: {"Department": "Finance"}
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	// (Updatable) Deprecated. The 'image' field has been deprecated. Use source_details.image in a CONTAINER_IMAGE source_details block instead. If both fields are specified, then 'source_details.image' will be used. Example: phx.ocir.io/ten/functions/function:0.0.1
	Image *string `json:"image,omitempty" tf:"image,omitempty"`

	// (Updatable) Deprecated. The 'image_digest' field has been deprecated. Use source_details.image_digest in a CONTAINER_IMAGE source_details block instead. If both fields are specified, then 'source_details.image_digest' will be used. Example: sha256:ca0eeb6fb05351dfc8759c20733c91def84cb8007aa89a5bf606bc8b315b9fc7
	ImageDigest *string `json:"imageDigest,omitempty" tf:"image_digest,omitempty"`

	// (Updatable) Maximum usable memory for the function (MiB).
	MemoryInMbs *string `json:"memoryInMbs,omitempty" tf:"memory_in_mbs,omitempty"`

	// (Updatable) Define the strategy for provisioned concurrency for the function.
	ProvisionedConcurrencyConfig []ProvisionedConcurrencyConfigInitParameters `json:"provisionedConcurrencyConfig,omitempty" tf:"provisioned_concurrency_config,omitempty"`

	// (Updatable) The source details for creating the Function. The function can be created from various sources.
	SourceDetails []SourceDetailsInitParameters `json:"sourceDetails,omitempty" tf:"source_details,omitempty"`

	// (Updatable) An object that represents the destination to which Oracle Functions will send an invocation record with the details of the successful detached function invocation. A stream is an example of a success destination.  Example: {"kind": "STREAM", "streamId": "stream_OCID"}
	SuccessDestination []SuccessDestinationInitParameters `json:"successDestination,omitempty" tf:"success_destination,omitempty"`

	// (Updatable) Timeout for executions of the function. Value in seconds.
	TimeoutInSeconds *float64 `json:"timeoutInSeconds,omitempty" tf:"timeout_in_seconds,omitempty"`

	// (Updatable) Define the tracing configuration for a function.
	TraceConfig []FunctionTraceConfigInitParameters `json:"traceConfig,omitempty" tf:"trace_config,omitempty"`
}

type FunctionObservation struct {

	// The OCID of the application this function belongs to.
	ApplicationID *string `json:"applicationId,omitempty" tf:"application_id,omitempty"`

	// The OCID of the compartment that contains the function.
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// (Updatable) Function configuration. These values are passed on to the function as environment variables, this overrides application configuration values. Keys must be ASCII strings consisting solely of letters, digits, and the '_' (underscore) character, and must not begin with a digit. Values should be limited to printable unicode characters.  Example: {"MY_FUNCTION_CONFIG": "ConfVal"}
	// +mapType=granular
	Config map[string]*string `json:"config,omitempty" tf:"config,omitempty"`

	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see Resource Tags.  Example: {"Operations.CostCenter": "42"}
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// (Updatable) Timeout for detached function invocations. Value in seconds.
	DetachedModeTimeoutInSeconds *float64 `json:"detachedModeTimeoutInSeconds,omitempty" tf:"detached_mode_timeout_in_seconds,omitempty"`

	// The display name of the function. The display name must be unique within the application containing the function. Avoid entering confidential information.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Updatable) An object that represents the destination to which Oracle Functions will send an invocation record with the details of the error of the failed detached function invocation. A notification is an example of a failure destination.  Example: {"kind": "NOTIFICATION", "topicId": "topic_OCID"}
	FailureDestination []FailureDestinationObservation `json:"failureDestination,omitempty" tf:"failure_destination,omitempty"`

	// (Updatable) Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace. For more information, see Resource Tags.  Example: {"Department": "Finance"}
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	// The OCID of the function.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Updatable) Deprecated. The 'image' field has been deprecated. Use source_details.image in a CONTAINER_IMAGE source_details block instead. If both fields are specified, then 'source_details.image' will be used. Example: phx.ocir.io/ten/functions/function:0.0.1
	Image *string `json:"image,omitempty" tf:"image,omitempty"`

	// (Updatable) Deprecated. The 'image_digest' field has been deprecated. Use source_details.image_digest in a CONTAINER_IMAGE source_details block instead. If both fields are specified, then 'source_details.image_digest' will be used. Example: sha256:ca0eeb6fb05351dfc8759c20733c91def84cb8007aa89a5bf606bc8b315b9fc7
	ImageDigest *string `json:"imageDigest,omitempty" tf:"image_digest,omitempty"`

	// The base https invoke URL to set on a client in order to invoke a function. This URL will never change over the lifetime of the function and can be cached.
	InvokeEndpoint *string `json:"invokeEndpoint,omitempty" tf:"invoke_endpoint,omitempty"`

	// (Updatable) Maximum usable memory for the function (MiB).
	MemoryInMbs *string `json:"memoryInMbs,omitempty" tf:"memory_in_mbs,omitempty"`

	// (Updatable) Define the strategy for provisioned concurrency for the function.
	ProvisionedConcurrencyConfig []ProvisionedConcurrencyConfigObservation `json:"provisionedConcurrencyConfig,omitempty" tf:"provisioned_concurrency_config,omitempty"`

	// The processor shape (GENERIC_X86/GENERIC_ARM) on which to run functions in the application, extracted from the image manifest.
	Shape *string `json:"shape,omitempty" tf:"shape,omitempty"`

	// (Updatable) The source details for creating the Function. The function can be created from various sources.
	SourceDetails []SourceDetailsObservation `json:"sourceDetails,omitempty" tf:"source_details,omitempty"`

	// The current state of the function.
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// (Updatable) An object that represents the destination to which Oracle Functions will send an invocation record with the details of the successful detached function invocation. A stream is an example of a success destination.  Example: {"kind": "STREAM", "streamId": "stream_OCID"}
	SuccessDestination []SuccessDestinationObservation `json:"successDestination,omitempty" tf:"success_destination,omitempty"`

	// The time the function was created, expressed in RFC 3339 timestamp format.  Example: 2018-09-12T22:47:12.613Z
	TimeCreated *string `json:"timeCreated,omitempty" tf:"time_created,omitempty"`

	// The time the function was updated, expressed in RFC 3339 timestamp format.  Example: 2018-09-12T22:47:12.613Z
	TimeUpdated *string `json:"timeUpdated,omitempty" tf:"time_updated,omitempty"`

	// (Updatable) Timeout for executions of the function. Value in seconds.
	TimeoutInSeconds *float64 `json:"timeoutInSeconds,omitempty" tf:"timeout_in_seconds,omitempty"`

	// (Updatable) Define the tracing configuration for a function.
	TraceConfig []FunctionTraceConfigObservation `json:"traceConfig,omitempty" tf:"trace_config,omitempty"`
}

type FunctionParameters struct {

	// The OCID of the application this function belongs to.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/functions/v1alpha1.Application
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	ApplicationID *string `json:"applicationId,omitempty" tf:"application_id,omitempty"`

	// Reference to a Application in functions to populate applicationId.
	// +kubebuilder:validation:Optional
	ApplicationIDRef *v1.NamespacedReference `json:"applicationIdRef,omitempty" tf:"-"`

	// Selector for a Application in functions to populate applicationId.
	// +kubebuilder:validation:Optional
	ApplicationIDSelector *v1.NamespacedSelector `json:"applicationIdSelector,omitempty" tf:"-"`

	// (Updatable) Function configuration. These values are passed on to the function as environment variables, this overrides application configuration values. Keys must be ASCII strings consisting solely of letters, digits, and the '_' (underscore) character, and must not begin with a digit. Values should be limited to printable unicode characters.  Example: {"MY_FUNCTION_CONFIG": "ConfVal"}
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Config map[string]*string `json:"config,omitempty" tf:"config,omitempty"`

	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see Resource Tags.  Example: {"Operations.CostCenter": "42"}
	// +kubebuilder:validation:Optional
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// (Updatable) Timeout for detached function invocations. Value in seconds.
	// +kubebuilder:validation:Optional
	DetachedModeTimeoutInSeconds *float64 `json:"detachedModeTimeoutInSeconds,omitempty" tf:"detached_mode_timeout_in_seconds,omitempty"`

	// The display name of the function. The display name must be unique within the application containing the function. Avoid entering confidential information.
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Updatable) An object that represents the destination to which Oracle Functions will send an invocation record with the details of the error of the failed detached function invocation. A notification is an example of a failure destination.  Example: {"kind": "NOTIFICATION", "topicId": "topic_OCID"}
	// +kubebuilder:validation:Optional
	FailureDestination []FailureDestinationParameters `json:"failureDestination,omitempty" tf:"failure_destination,omitempty"`

	// (Updatable) Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace. For more information, see Resource Tags.  Example: {"Department": "Finance"}
	// +kubebuilder:validation:Optional
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	// (Updatable) Deprecated. The 'image' field has been deprecated. Use source_details.image in a CONTAINER_IMAGE source_details block instead. If both fields are specified, then 'source_details.image' will be used. Example: phx.ocir.io/ten/functions/function:0.0.1
	// +kubebuilder:validation:Optional
	Image *string `json:"image,omitempty" tf:"image,omitempty"`

	// (Updatable) Deprecated. The 'image_digest' field has been deprecated. Use source_details.image_digest in a CONTAINER_IMAGE source_details block instead. If both fields are specified, then 'source_details.image_digest' will be used. Example: sha256:ca0eeb6fb05351dfc8759c20733c91def84cb8007aa89a5bf606bc8b315b9fc7
	// +kubebuilder:validation:Optional
	ImageDigest *string `json:"imageDigest,omitempty" tf:"image_digest,omitempty"`

	// (Updatable) Maximum usable memory for the function (MiB).
	// +kubebuilder:validation:Optional
	MemoryInMbs *string `json:"memoryInMbs,omitempty" tf:"memory_in_mbs,omitempty"`

	// (Updatable) Define the strategy for provisioned concurrency for the function.
	// +kubebuilder:validation:Optional
	ProvisionedConcurrencyConfig []ProvisionedConcurrencyConfigParameters `json:"provisionedConcurrencyConfig,omitempty" tf:"provisioned_concurrency_config,omitempty"`

	// (Updatable) The source details for creating the Function. The function can be created from various sources.
	// +kubebuilder:validation:Optional
	SourceDetails []SourceDetailsParameters `json:"sourceDetails,omitempty" tf:"source_details,omitempty"`

	// (Updatable) An object that represents the destination to which Oracle Functions will send an invocation record with the details of the successful detached function invocation. A stream is an example of a success destination.  Example: {"kind": "STREAM", "streamId": "stream_OCID"}
	// +kubebuilder:validation:Optional
	SuccessDestination []SuccessDestinationParameters `json:"successDestination,omitempty" tf:"success_destination,omitempty"`

	// (Updatable) Timeout for executions of the function. Value in seconds.
	// +kubebuilder:validation:Optional
	TimeoutInSeconds *float64 `json:"timeoutInSeconds,omitempty" tf:"timeout_in_seconds,omitempty"`

	// (Updatable) Define the tracing configuration for a function.
	// +kubebuilder:validation:Optional
	TraceConfig []FunctionTraceConfigParameters `json:"traceConfig,omitempty" tf:"trace_config,omitempty"`
}

type FunctionTraceConfigInitParameters struct {

	// (Updatable) Define if tracing is enabled for the resource.
	IsEnabled *bool `json:"isEnabled,omitempty" tf:"is_enabled,omitempty"`
}

type FunctionTraceConfigObservation struct {

	// (Updatable) Define if tracing is enabled for the resource.
	IsEnabled *bool `json:"isEnabled,omitempty" tf:"is_enabled,omitempty"`
}

type FunctionTraceConfigParameters struct {

	// (Updatable) Define if tracing is enabled for the resource.
	// +kubebuilder:validation:Optional
	IsEnabled *bool `json:"isEnabled,omitempty" tf:"is_enabled,omitempty"`
}

type ProvisionedConcurrencyConfigInitParameters struct {

	// (Updatable) Configuration specifying a constant amount of provisioned concurrency.
	Count *float64 `json:"count,omitempty" tf:"count,omitempty"`

	// (Updatable) The strategy for provisioned concurrency to be used.
	Strategy *string `json:"strategy,omitempty" tf:"strategy,omitempty"`
}

type ProvisionedConcurrencyConfigObservation struct {

	// (Updatable) Configuration specifying a constant amount of provisioned concurrency.
	Count *float64 `json:"count,omitempty" tf:"count,omitempty"`

	// (Updatable) The strategy for provisioned concurrency to be used.
	Strategy *string `json:"strategy,omitempty" tf:"strategy,omitempty"`
}

type ProvisionedConcurrencyConfigParameters struct {

	// (Updatable) Configuration specifying a constant amount of provisioned concurrency.
	// +kubebuilder:validation:Optional
	Count *float64 `json:"count,omitempty" tf:"count,omitempty"`

	// (Updatable) The strategy for provisioned concurrency to be used.
	// +kubebuilder:validation:Optional
	Strategy *string `json:"strategy" tf:"strategy,omitempty"`
}

type RuntimeConfigInitParameters struct {

	// (Updatable) The name of the FunctionsRuntime this function is to be associated with.
	FunctionsRuntimeName *string `json:"functionsRuntimeName,omitempty" tf:"functions_runtime_name,omitempty"`

	// (Updatable) The OCID of the FunctionsRuntimeVersion to use for the Function in manual mode.
	FunctionsRuntimeVersionID *string `json:"functionsRuntimeVersionId,omitempty" tf:"functions_runtime_version_id,omitempty"`

	// (Updatable) Type of the FunctionsRuntime Config. Possible values: FUNCTION_UPDATE and MANUAL.
	RuntimeConfigType *string `json:"runtimeConfigType,omitempty" tf:"runtime_config_type,omitempty"`
}

type RuntimeConfigObservation struct {

	// (Updatable) The name of the FunctionsRuntime this function is to be associated with.
	FunctionsRuntimeName *string `json:"functionsRuntimeName,omitempty" tf:"functions_runtime_name,omitempty"`

	// (Updatable) The OCID of the FunctionsRuntimeVersion to use for the Function in manual mode.
	FunctionsRuntimeVersionID *string `json:"functionsRuntimeVersionId,omitempty" tf:"functions_runtime_version_id,omitempty"`

	// (Updatable) Type of the FunctionsRuntime Config. Possible values: FUNCTION_UPDATE and MANUAL.
	RuntimeConfigType *string `json:"runtimeConfigType,omitempty" tf:"runtime_config_type,omitempty"`
}

type RuntimeConfigParameters struct {

	// (Updatable) The name of the FunctionsRuntime this function is to be associated with.
	// +kubebuilder:validation:Optional
	FunctionsRuntimeName *string `json:"functionsRuntimeName" tf:"functions_runtime_name,omitempty"`

	// (Updatable) The OCID of the FunctionsRuntimeVersion to use for the Function in manual mode.
	// +kubebuilder:validation:Optional
	FunctionsRuntimeVersionID *string `json:"functionsRuntimeVersionId,omitempty" tf:"functions_runtime_version_id,omitempty"`

	// (Updatable) Type of the FunctionsRuntime Config. Possible values: FUNCTION_UPDATE and MANUAL.
	// +kubebuilder:validation:Optional
	RuntimeConfigType *string `json:"runtimeConfigType" tf:"runtime_config_type,omitempty"`
}

type SourceDetailsInitParameters struct {

	// (Updatable) The details required to create an Archive-based function source.  This mode is used when the function code is provided as an archive, either from Object Storage or directly uploaded by the API caller.  It is suitable for scenarios where the function code is packaged as a single archive file.
	ArchiveSourceDetails []ArchiveSourceDetailsInitParameters `json:"archiveSourceDetails,omitempty" tf:"archive_source_details,omitempty"`

	// (Applicable when source_type=ARCHIVE) (Updatable) The function handler that is executed when the function is invoked. The value of this field depends on the runtime used
	Handler *string `json:"handler,omitempty" tf:"handler,omitempty"`

	// (Updatable) Deprecated. The 'image' field has been deprecated. Use source_details.image in a CONTAINER_IMAGE source_details block instead. If both fields are specified, then 'source_details.image' will be used. Example: phx.ocir.io/ten/functions/function:0.0.1
	Image *string `json:"image,omitempty" tf:"image,omitempty"`

	// (Updatable) Deprecated. The 'image_digest' field has been deprecated. Use source_details.image_digest in a CONTAINER_IMAGE source_details block instead. If both fields are specified, then 'source_details.image_digest' will be used. Example: sha256:ca0eeb6fb05351dfc8759c20733c91def84cb8007aa89a5bf606bc8b315b9fc7
	ImageDigest *string `json:"imageDigest,omitempty" tf:"image_digest,omitempty"`

	// The OCID of the PbfListing this function is sourced from.
	PbfListingID *string `json:"pbfListingId,omitempty" tf:"pbf_listing_id,omitempty"`

	// (Updatable) FunctionsRuntime configuration used to create a function.
	RuntimeConfig []RuntimeConfigInitParameters `json:"runtimeConfig,omitempty" tf:"runtime_config,omitempty"`

	// (Updatable) Type of the Function Source. Possible values: CONTAINER_IMAGE, PRE_BUILT_FUNCTIONS and ARCHIVE.
	SourceType *string `json:"sourceType,omitempty" tf:"source_type,omitempty"`
}

type SourceDetailsObservation struct {

	// (Updatable) The details required to create an Archive-based function source.  This mode is used when the function code is provided as an archive, either from Object Storage or directly uploaded by the API caller.  It is suitable for scenarios where the function code is packaged as a single archive file.
	ArchiveSourceDetails []ArchiveSourceDetailsObservation `json:"archiveSourceDetails,omitempty" tf:"archive_source_details,omitempty"`

	// (Applicable when source_type=ARCHIVE) (Updatable) The function handler that is executed when the function is invoked. The value of this field depends on the runtime used
	Handler *string `json:"handler,omitempty" tf:"handler,omitempty"`

	// (Updatable) Deprecated. The 'image' field has been deprecated. Use source_details.image in a CONTAINER_IMAGE source_details block instead. If both fields are specified, then 'source_details.image' will be used. Example: phx.ocir.io/ten/functions/function:0.0.1
	Image *string `json:"image,omitempty" tf:"image,omitempty"`

	// (Updatable) Deprecated. The 'image_digest' field has been deprecated. Use source_details.image_digest in a CONTAINER_IMAGE source_details block instead. If both fields are specified, then 'source_details.image_digest' will be used. Example: sha256:ca0eeb6fb05351dfc8759c20733c91def84cb8007aa89a5bf606bc8b315b9fc7
	ImageDigest *string `json:"imageDigest,omitempty" tf:"image_digest,omitempty"`

	// The OCID of the PbfListing this function is sourced from.
	PbfListingID *string `json:"pbfListingId,omitempty" tf:"pbf_listing_id,omitempty"`

	// (Updatable) FunctionsRuntime configuration used to create a function.
	RuntimeConfig []RuntimeConfigObservation `json:"runtimeConfig,omitempty" tf:"runtime_config,omitempty"`

	// The SHA256 hash of the function source code archive, base64-encoded.
	SourceCodeSha256 *string `json:"sourceCodeSha256,omitempty" tf:"source_code_sha256,omitempty"`

	// (Updatable) Type of the Function Source. Possible values: CONTAINER_IMAGE, PRE_BUILT_FUNCTIONS and ARCHIVE.
	SourceType *string `json:"sourceType,omitempty" tf:"source_type,omitempty"`
}

type SourceDetailsParameters struct {

	// (Updatable) The details required to create an Archive-based function source.  This mode is used when the function code is provided as an archive, either from Object Storage or directly uploaded by the API caller.  It is suitable for scenarios where the function code is packaged as a single archive file.
	// +kubebuilder:validation:Optional
	ArchiveSourceDetails []ArchiveSourceDetailsParameters `json:"archiveSourceDetails,omitempty" tf:"archive_source_details,omitempty"`

	// (Applicable when source_type=ARCHIVE) (Updatable) The function handler that is executed when the function is invoked. The value of this field depends on the runtime used
	// +kubebuilder:validation:Optional
	Handler *string `json:"handler,omitempty" tf:"handler,omitempty"`

	// (Updatable) Deprecated. The 'image' field has been deprecated. Use source_details.image in a CONTAINER_IMAGE source_details block instead. If both fields are specified, then 'source_details.image' will be used. Example: phx.ocir.io/ten/functions/function:0.0.1
	// +kubebuilder:validation:Optional
	Image *string `json:"image,omitempty" tf:"image,omitempty"`

	// (Updatable) Deprecated. The 'image_digest' field has been deprecated. Use source_details.image_digest in a CONTAINER_IMAGE source_details block instead. If both fields are specified, then 'source_details.image_digest' will be used. Example: sha256:ca0eeb6fb05351dfc8759c20733c91def84cb8007aa89a5bf606bc8b315b9fc7
	// +kubebuilder:validation:Optional
	ImageDigest *string `json:"imageDigest,omitempty" tf:"image_digest,omitempty"`

	// The OCID of the PbfListing this function is sourced from.
	// +kubebuilder:validation:Optional
	PbfListingID *string `json:"pbfListingId,omitempty" tf:"pbf_listing_id,omitempty"`

	// (Updatable) FunctionsRuntime configuration used to create a function.
	// +kubebuilder:validation:Optional
	RuntimeConfig []RuntimeConfigParameters `json:"runtimeConfig,omitempty" tf:"runtime_config,omitempty"`

	// (Updatable) Type of the Function Source. Possible values: CONTAINER_IMAGE, PRE_BUILT_FUNCTIONS and ARCHIVE.
	// +kubebuilder:validation:Optional
	SourceType *string `json:"sourceType" tf:"source_type,omitempty"`
}

type SuccessDestinationInitParameters struct {

	// (Applicable when kind=QUEUE) (Updatable) The ID of the channel in the queue.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/mysql/v1alpha1.MysqlChannel
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	ChannelID *string `json:"channelId,omitempty" tf:"channel_id,omitempty"`

	// Reference to a MysqlChannel in mysql to populate channelId.
	// +kubebuilder:validation:Optional
	ChannelIDRef *v1.NamespacedReference `json:"channelIdRef,omitempty" tf:"-"`

	// Selector for a MysqlChannel in mysql to populate channelId.
	// +kubebuilder:validation:Optional
	ChannelIDSelector *v1.NamespacedSelector `json:"channelIdSelector,omitempty" tf:"-"`

	// (Updatable) The type of destination for the response to a failed detached function invocation.
	Kind *string `json:"kind,omitempty" tf:"kind,omitempty"`

	// (Updatable) The OCID of the queue.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/queue/v1alpha1.Queue
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	QueueID *string `json:"queueId,omitempty" tf:"queue_id,omitempty"`

	// Reference to a Queue in queue to populate queueId.
	// +kubebuilder:validation:Optional
	QueueIDRef *v1.NamespacedReference `json:"queueIdRef,omitempty" tf:"-"`

	// Selector for a Queue in queue to populate queueId.
	// +kubebuilder:validation:Optional
	QueueIDSelector *v1.NamespacedSelector `json:"queueIdSelector,omitempty" tf:"-"`

	// (Updatable) The OCID of the stream.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/streaming/v1alpha1.Stream
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	StreamID *string `json:"streamId,omitempty" tf:"stream_id,omitempty"`

	// Reference to a Stream in streaming to populate streamId.
	// +kubebuilder:validation:Optional
	StreamIDRef *v1.NamespacedReference `json:"streamIdRef,omitempty" tf:"-"`

	// Selector for a Stream in streaming to populate streamId.
	// +kubebuilder:validation:Optional
	StreamIDSelector *v1.NamespacedSelector `json:"streamIdSelector,omitempty" tf:"-"`

	// (Updatable) The OCID of the topic.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/ons/v1alpha1.NotificationTopic
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	TopicID *string `json:"topicId,omitempty" tf:"topic_id,omitempty"`

	// Reference to a NotificationTopic in ons to populate topicId.
	// +kubebuilder:validation:Optional
	TopicIDRef *v1.NamespacedReference `json:"topicIdRef,omitempty" tf:"-"`

	// Selector for a NotificationTopic in ons to populate topicId.
	// +kubebuilder:validation:Optional
	TopicIDSelector *v1.NamespacedSelector `json:"topicIdSelector,omitempty" tf:"-"`
}

type SuccessDestinationObservation struct {

	// (Applicable when kind=QUEUE) (Updatable) The ID of the channel in the queue.
	ChannelID *string `json:"channelId,omitempty" tf:"channel_id,omitempty"`

	// (Updatable) The type of destination for the response to a failed detached function invocation.
	Kind *string `json:"kind,omitempty" tf:"kind,omitempty"`

	// (Updatable) The OCID of the queue.
	QueueID *string `json:"queueId,omitempty" tf:"queue_id,omitempty"`

	// (Updatable) The OCID of the stream.
	StreamID *string `json:"streamId,omitempty" tf:"stream_id,omitempty"`

	// (Updatable) The OCID of the topic.
	TopicID *string `json:"topicId,omitempty" tf:"topic_id,omitempty"`
}

type SuccessDestinationParameters struct {

	// (Applicable when kind=QUEUE) (Updatable) The ID of the channel in the queue.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/mysql/v1alpha1.MysqlChannel
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	ChannelID *string `json:"channelId,omitempty" tf:"channel_id,omitempty"`

	// Reference to a MysqlChannel in mysql to populate channelId.
	// +kubebuilder:validation:Optional
	ChannelIDRef *v1.NamespacedReference `json:"channelIdRef,omitempty" tf:"-"`

	// Selector for a MysqlChannel in mysql to populate channelId.
	// +kubebuilder:validation:Optional
	ChannelIDSelector *v1.NamespacedSelector `json:"channelIdSelector,omitempty" tf:"-"`

	// (Updatable) The type of destination for the response to a failed detached function invocation.
	// +kubebuilder:validation:Optional
	Kind *string `json:"kind" tf:"kind,omitempty"`

	// (Updatable) The OCID of the queue.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/queue/v1alpha1.Queue
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	QueueID *string `json:"queueId,omitempty" tf:"queue_id,omitempty"`

	// Reference to a Queue in queue to populate queueId.
	// +kubebuilder:validation:Optional
	QueueIDRef *v1.NamespacedReference `json:"queueIdRef,omitempty" tf:"-"`

	// Selector for a Queue in queue to populate queueId.
	// +kubebuilder:validation:Optional
	QueueIDSelector *v1.NamespacedSelector `json:"queueIdSelector,omitempty" tf:"-"`

	// (Updatable) The OCID of the stream.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/streaming/v1alpha1.Stream
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	StreamID *string `json:"streamId,omitempty" tf:"stream_id,omitempty"`

	// Reference to a Stream in streaming to populate streamId.
	// +kubebuilder:validation:Optional
	StreamIDRef *v1.NamespacedReference `json:"streamIdRef,omitempty" tf:"-"`

	// Selector for a Stream in streaming to populate streamId.
	// +kubebuilder:validation:Optional
	StreamIDSelector *v1.NamespacedSelector `json:"streamIdSelector,omitempty" tf:"-"`

	// (Updatable) The OCID of the topic.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/ons/v1alpha1.NotificationTopic
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	TopicID *string `json:"topicId,omitempty" tf:"topic_id,omitempty"`

	// Reference to a NotificationTopic in ons to populate topicId.
	// +kubebuilder:validation:Optional
	TopicIDRef *v1.NamespacedReference `json:"topicIdRef,omitempty" tf:"-"`

	// Selector for a NotificationTopic in ons to populate topicId.
	// +kubebuilder:validation:Optional
	TopicIDSelector *v1.NamespacedSelector `json:"topicIdSelector,omitempty" tf:"-"`
}

// FunctionSpec defines the desired state of Function
type FunctionSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            FunctionParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider FunctionInitParameters `json:"initProvider,omitempty"`
}

// FunctionStatus defines the observed state of Function.
type FunctionStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        FunctionObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Function is the Schema for the Functions API. Provides the Function resource in Oracle Cloud Infrastructure Functions service
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,oci}
type Function struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.displayName) || (has(self.initProvider) && has(self.initProvider.displayName))",message="spec.forProvider.displayName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.memoryInMbs) || (has(self.initProvider) && has(self.initProvider.memoryInMbs))",message="spec.forProvider.memoryInMbs is a required parameter"
	Spec   FunctionSpec   `json:"spec"`
	Status FunctionStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// FunctionList contains a list of Functions
type FunctionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Function `json:"items"`
}

// Repository type metadata.
var (
	Function_Kind             = "Function"
	Function_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Function_Kind}.String()
	Function_KindAPIVersion   = Function_Kind + "." + CRDGroupVersion.String()
	Function_GroupVersionKind = CRDGroupVersion.WithKind(Function_Kind)
)

func init() {
	SchemeBuilder.Register(&Function{}, &FunctionList{})
}
