/*
Copyright 2021 Upbound Inc.
*/

package main

import (
	"fmt"
	"go/format"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/crossplane/upjet/v2/pkg/pipeline"

	"github.com/oracle/provider-oci/config"
	"github.com/oracle/provider-oci/hack"
)

func main() {
	if len(os.Args) < 2 || os.Args[1] == "" {
		panic("root directory is required to be given as argument")
	}
	rootDir := os.Args[1]
	absRootDir, err := filepath.Abs(rootDir)
	if err != nil {
		panic(fmt.Sprintf("cannot calculate the absolute path with %s", rootDir))
	}
	pipeline.Run(config.GetProviderForGeneration(), config.GetProviderNamespacedForGeneration(), absRootDir)
	if err := registerTerraformMetricRecorders(absRootDir); err != nil {
		panic(fmt.Sprintf("cannot register generated Terraform metric recorders: %v", err))
	}
	if err := generateRuntimeTerraformResourceManifest(absRootDir); err != nil {
		panic(fmt.Sprintf("cannot generate runtime Terraform resource manifest: %v", err))
	}
	if err := generateProviderConfigMain(absRootDir); err != nil {
		panic(fmt.Sprintf("cannot generate lightweight ProviderConfig main: %v", err))
	}
}

var terraformMetricRecorderPattern = regexp.MustCompile(`tjcontroller\.WithTerraformPluginSDKAsyncMetricRecorder\(metrics\.NewMetricRecorder\(([^,\n]+), mgr, o\.PollInterval\)\)`)

var terraformRuntimeResourcePattern = regexp.MustCompile(`o\.Provider\.Resources\["([^"]+)"\]`)

func generateRuntimeTerraformResourceManifest(rootDir string) error {
	controllerRoot := filepath.Join(rootDir, "internal", "controller", "cluster")
	resourcesByService := map[string]map[string]struct{}{}
	allResources := map[string]struct{}{}
	err := filepath.WalkDir(controllerRoot, func(path string, entry fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() || entry.Name() != "zz_controller.go" {
			return nil
		}

		relativePath, err := filepath.Rel(controllerRoot, path)
		if err != nil {
			return err
		}
		parts := strings.Split(relativePath, string(filepath.Separator))
		if len(parts) < 3 {
			return fmt.Errorf("cannot determine provider service from controller path %s", path)
		}
		service := parts[0]

		content, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		matches := terraformRuntimeResourcePattern.FindAllSubmatch(content, -1)
		if len(matches) != 1 {
			return fmt.Errorf("%s contains %d Terraform provider resource lookups, want 1", path, len(matches))
		}
		resourceName := string(matches[0][1])
		if resourcesByService[service] == nil {
			resourcesByService[service] = map[string]struct{}{}
		}
		resourcesByService[service][resourceName] = struct{}{}
		allResources[resourceName] = struct{}{}
		return nil
	})
	if err != nil {
		return err
	}
	if len(resourcesByService) == 0 {
		return fmt.Errorf("no generated Terraform resource controllers found under %s", controllerRoot)
	}
	if err := validateNamespacedRuntimeTerraformResources(rootDir, resourcesByService); err != nil {
		return err
	}
	resourcesByService["monolith"] = allResources

	services := make([]string, 0, len(resourcesByService))
	for service := range resourcesByService {
		services = append(services, service)
	}
	sort.Strings(services)

	var output strings.Builder
	output.WriteString("// Code generated by provider-oci. DO NOT EDIT.\n\npackage config\n\n")
	output.WriteString("// runtimeTerraformResources maps generated provider service processes to the\n")
	output.WriteString("// Terraform resources whose controllers they run.\n")
	output.WriteString("var runtimeTerraformResources = map[string][]string{\n")
	for _, service := range services {
		resources := make([]string, 0, len(resourcesByService[service]))
		for resourceName := range resourcesByService[service] {
			resources = append(resources, resourceName)
		}
		sort.Strings(resources)
		fmt.Fprintf(&output, "\t%q: {\n", service)
		for _, resourceName := range resources {
			fmt.Fprintf(&output, "\t\t%q,\n", resourceName)
		}
		output.WriteString("\t},\n")
	}
	output.WriteString("}\n")

	formatted, err := format.Source([]byte(output.String()))
	if err != nil {
		return fmt.Errorf("cannot format runtime Terraform resource manifest: %w", err)
	}
	return os.WriteFile(filepath.Join(rootDir, "config", "runtime_resources_generated.go"), formatted, 0o644)
}

func validateNamespacedRuntimeTerraformResources(rootDir string, clusterResources map[string]map[string]struct{}) error {
	controllerRoot := filepath.Join(rootDir, "internal", "controller", "namespaced")
	namespacedResources := map[string]map[string]struct{}{}
	err := filepath.WalkDir(controllerRoot, func(path string, entry fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() || entry.Name() != "zz_controller.go" {
			return nil
		}

		relativePath, err := filepath.Rel(controllerRoot, path)
		if err != nil {
			return err
		}
		parts := strings.Split(relativePath, string(filepath.Separator))
		if len(parts) < 3 {
			return fmt.Errorf("cannot determine provider service from controller path %s", path)
		}
		service := parts[0]

		content, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		matches := terraformRuntimeResourcePattern.FindAllSubmatch(content, -1)
		if len(matches) != 1 {
			return fmt.Errorf("%s contains %d Terraform provider resource lookups, want 1", path, len(matches))
		}
		if namespacedResources[service] == nil {
			namespacedResources[service] = map[string]struct{}{}
		}
		namespacedResources[service][string(matches[0][1])] = struct{}{}
		return nil
	})
	if err != nil {
		return err
	}

	for service, resources := range clusterResources {
		namespaced := namespacedResources[service]
		if len(namespaced) != len(resources) {
			return fmt.Errorf("service %q has %d cluster-scoped and %d namespaced Terraform resource controllers", service, len(resources), len(namespaced))
		}
		for resourceName := range resources {
			if _, ok := namespaced[resourceName]; !ok {
				return fmt.Errorf("service %q Terraform resource %q has no matching namespaced controller", service, resourceName)
			}
		}
		delete(namespacedResources, service)
	}
	if len(namespacedResources) != 0 {
		return fmt.Errorf("namespaced Terraform controller services have no cluster-scoped counterpart: %v", namespacedResources)
	}
	return nil
}

func generateProviderConfigMain(rootDir string) error {
	formatted, err := format.Source([]byte(hack.ConfigMainTemplate))
	if err != nil {
		return fmt.Errorf("cannot format lightweight ProviderConfig main: %w", err)
	}
	return os.WriteFile(filepath.Join(rootDir, "cmd", "provider", "config", "zz_main.go"), formatted, 0o644)
}

func registerTerraformMetricRecorders(rootDir string) error {
	controllerRoot := filepath.Join(rootDir, "internal", "controller")
	return filepath.WalkDir(controllerRoot, func(path string, entry fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() || entry.Name() != "zz_controller.go" {
			return nil
		}
		return registerTerraformMetricRecorder(path)
	})
}

func registerTerraformMetricRecorder(path string) error {
	content, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	matches := terraformMetricRecorderPattern.FindSubmatch(content)
	if len(matches) == 0 {
		return nil
	}
	if len(terraformMetricRecorderPattern.FindAll(content, -1)) != 1 {
		return fmt.Errorf("%s contains multiple Terraform metric recorder expressions", path)
	}

	const optionsDeclaration = "\topts := []managed.ReconcilerOption{\n"
	if strings.Count(string(content), optionsDeclaration) != 1 {
		return fmt.Errorf("%s does not contain one reconciler options declaration", path)
	}
	registration := fmt.Sprintf(
		"\tmetricRecorder := metrics.NewMetricRecorder(%s, mgr, o.PollInterval)\n"+
			"\tif err := mgr.Add(metricRecorder); err != nil {\n"+
			"\t\treturn errors.Wrap(err, \"cannot register Terraform metric recorder\")\n"+
			"\t}\n",
		matches[1],
	)
	updated := strings.Replace(string(content), optionsDeclaration, registration+optionsDeclaration, 1)
	updated = terraformMetricRecorderPattern.ReplaceAllString(updated, "tjcontroller.WithTerraformPluginSDKAsyncMetricRecorder(metricRecorder)")

	info, err := os.Stat(path)
	if err != nil {
		return err
	}
	return os.WriteFile(path, []byte(updated), info.Mode().Perm())
}
