/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type CryptoAssessmentInitParameters struct {

	// (Updatable) The OCID of the compartment that contains the crypto assessment.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/identity/v1alpha1.Compartment
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// Reference to a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDRef *v1.NamespacedReference `json:"compartmentIdRef,omitempty" tf:"-"`

	// Selector for a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDSelector *v1.NamespacedSelector `json:"compartmentIdSelector,omitempty" tf:"-"`

	// The OCID of the crypto assessment.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/datasafe/v1alpha1.CryptoAssessment
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	CryptoAssessmentID *string `json:"cryptoAssessmentId,omitempty" tf:"crypto_assessment_id,omitempty"`

	// Reference to a CryptoAssessment in datasafe to populate cryptoAssessmentId.
	// +kubebuilder:validation:Optional
	CryptoAssessmentIDRef *v1.NamespacedReference `json:"cryptoAssessmentIdRef,omitempty" tf:"-"`

	// Selector for a CryptoAssessment in datasafe to populate cryptoAssessmentId.
	// +kubebuilder:validation:Optional
	CryptoAssessmentIDSelector *v1.NamespacedSelector `json:"cryptoAssessmentIdSelector,omitempty" tf:"-"`

	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see Resource Tags Example: {"Operations.CostCenter": "42"}
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// (Updatable) The display name of the crypto assessment.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Updatable) Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace. For more information, see Resource Tags  Example: {"Department": "Finance"}
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	// (Updatable) Indicates whether scheduled execution is active for this latest crypto assessment. When set to true, the existing schedule is used unless a new schedule is provided. When set to false, the schedule value is retained but scheduled execution is paused. Schedule state updates are supported only for assessments of type LATEST.
	IsAssessmentScheduled *bool `json:"isAssessmentScheduled,omitempty" tf:"is_assessment_scheduled,omitempty"`

	// (Updatable) Updates the schedule associated with this latest crypto assessment. The schedule uses the format: ;
	Schedule *string `json:"schedule,omitempty" tf:"schedule,omitempty"`
}

type CryptoAssessmentObservation struct {

	// (Updatable) The OCID of the compartment that contains the crypto assessment.
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// The OCID of the crypto assessment.
	CryptoAssessmentID *string `json:"cryptoAssessmentId,omitempty" tf:"crypto_assessment_id,omitempty"`

	// Cryptographic posture details captured by the assessment.
	CryptoPosture []CryptoPostureObservation `json:"cryptoPosture,omitempty" tf:"crypto_posture,omitempty"`

	// Cryptographic provider and version information observed on the target.
	CryptoProvider *string `json:"cryptoProvider,omitempty" tf:"crypto_provider,omitempty"`

	// The architecture of the assessed target database.
	DatabaseArchitecture *string `json:"databaseArchitecture,omitempty" tf:"database_architecture,omitempty"`

	// The name of the assessed target database.
	DatabaseName *string `json:"databaseName,omitempty" tf:"database_name,omitempty"`

	// The version of the assessed target database.
	DatabaseVersion *string `json:"databaseVersion,omitempty" tf:"database_version,omitempty"`

	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see Resource Tags Example: {"Operations.CostCenter": "42"}
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// The description of the crypto assessment.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Updatable) The display name of the crypto assessment.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Updatable) Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace. For more information, see Resource Tags  Example: {"Department": "Finance"}
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	// The OCID of the crypto assessment.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Updatable) Indicates whether scheduled execution is active for this latest crypto assessment. When set to true, the existing schedule is used unless a new schedule is provided. When set to false, the schedule value is retained but scheduled execution is paused. Schedule state updates are supported only for assessments of type LATEST.
	IsAssessmentScheduled *bool `json:"isAssessmentScheduled,omitempty" tf:"is_assessment_scheduled,omitempty"`

	// Number of crypto issues detected in this assessment.
	IssueCount *float64 `json:"issueCount,omitempty" tf:"issue_count,omitempty"`

	// Details about the current lifecycle state of the crypto assessment.
	LifecycleDetails *string `json:"lifecycleDetails,omitempty" tf:"lifecycle_details,omitempty"`

	// Overall posture category for the crypto assessment.
	PostureCategory *string `json:"postureCategory,omitempty" tf:"posture_category,omitempty"`

	// (Updatable) Updates the schedule associated with this latest crypto assessment. The schedule uses the format: ;
	Schedule *string `json:"schedule,omitempty" tf:"schedule,omitempty"`

	// The current lifecycle state of the crypto assessment.
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// System tags for this resource. Each key is predefined and scoped to a namespace. For more information, see Resource Tags. Example: {"orcl-cloud.free-tier-retained": "true"}
	// +mapType=granular
	SystemTags map[string]*string `json:"systemTags,omitempty" tf:"system_tags,omitempty"`

	// The OCID of the target database group. This is returned when targetType is TARGET_DATABASE_GROUP.
	TargetDatabaseGroupID *string `json:"targetDatabaseGroupId,omitempty" tf:"target_database_group_id,omitempty"`

	// The OCID of the target database.
	TargetID *string `json:"targetId,omitempty" tf:"target_id,omitempty"`

	// The target type of the crypto assessment.
	TargetType *string `json:"targetType,omitempty" tf:"target_type,omitempty"`

	// Number of assessed targets with one or more crypto issues. For a target database assessment, this value is 1 when the target has issues and 0 otherwise. For a target database group assessment, this value is the number of targets in the group that have issues.
	TargetsWithIssuesCount *float64 `json:"targetsWithIssuesCount,omitempty" tf:"targets_with_issues_count,omitempty"`

	// The date and time the crypto assessment was created, in RFC3339 format.
	TimeCreated *string `json:"timeCreated,omitempty" tf:"time_created,omitempty"`

	// The date and time the crypto posture was last assessed, in RFC3339 format.
	TimeLastAssessed *string `json:"timeLastAssessed,omitempty" tf:"time_last_assessed,omitempty"`

	// The date and time the crypto assessment was last updated, in RFC3339 format.
	TimeUpdated *string `json:"timeUpdated,omitempty" tf:"time_updated,omitempty"`

	// The actor that created the assessment.
	TriggeredBy *string `json:"triggeredBy,omitempty" tf:"triggered_by,omitempty"`

	// The type of this crypto assessment.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type CryptoAssessmentParameters struct {

	// (Updatable) The OCID of the compartment that contains the crypto assessment.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/identity/v1alpha1.Compartment
	// +kubebuilder:validation:Optional
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// Reference to a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDRef *v1.NamespacedReference `json:"compartmentIdRef,omitempty" tf:"-"`

	// Selector for a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDSelector *v1.NamespacedSelector `json:"compartmentIdSelector,omitempty" tf:"-"`

	// The OCID of the crypto assessment.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/datasafe/v1alpha1.CryptoAssessment
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	CryptoAssessmentID *string `json:"cryptoAssessmentId,omitempty" tf:"crypto_assessment_id,omitempty"`

	// Reference to a CryptoAssessment in datasafe to populate cryptoAssessmentId.
	// +kubebuilder:validation:Optional
	CryptoAssessmentIDRef *v1.NamespacedReference `json:"cryptoAssessmentIdRef,omitempty" tf:"-"`

	// Selector for a CryptoAssessment in datasafe to populate cryptoAssessmentId.
	// +kubebuilder:validation:Optional
	CryptoAssessmentIDSelector *v1.NamespacedSelector `json:"cryptoAssessmentIdSelector,omitempty" tf:"-"`

	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see Resource Tags Example: {"Operations.CostCenter": "42"}
	// +kubebuilder:validation:Optional
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// (Updatable) The display name of the crypto assessment.
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Updatable) Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace. For more information, see Resource Tags  Example: {"Department": "Finance"}
	// +kubebuilder:validation:Optional
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	// (Updatable) Indicates whether scheduled execution is active for this latest crypto assessment. When set to true, the existing schedule is used unless a new schedule is provided. When set to false, the schedule value is retained but scheduled execution is paused. Schedule state updates are supported only for assessments of type LATEST.
	// +kubebuilder:validation:Optional
	IsAssessmentScheduled *bool `json:"isAssessmentScheduled,omitempty" tf:"is_assessment_scheduled,omitempty"`

	// (Updatable) Updates the schedule associated with this latest crypto assessment. The schedule uses the format: ;
	// +kubebuilder:validation:Optional
	Schedule *string `json:"schedule,omitempty" tf:"schedule,omitempty"`
}

type CryptoPostureInitParameters struct {
}

type CryptoPostureObservation struct {

	// Backup encryption status observed for the assessment.
	BackupStatus *string `json:"backupStatus,omitempty" tf:"backup_status,omitempty"`

	// Number of encrypted backup pieces.
	EncryptedBackupPiecesCount *float64 `json:"encryptedBackupPiecesCount,omitempty" tf:"encrypted_backup_pieces_count,omitempty"`

	// Common FIPS mode configured for the assessment when the target uses common FIPS configuration.
	FipsModeConfigured *string `json:"fipsModeConfigured,omitempty" tf:"fips_mode_configured,omitempty"`

	// Overall FIPS status for the assessment when the target uses common FIPS configuration.
	FipsStatus *string `json:"fipsStatus,omitempty" tf:"fips_status,omitempty"`

	// Network encryption details.
	NetworkEncryption []*string `json:"networkEncryption,omitempty" tf:"network_encryption,omitempty"`

	// Native network encryption posture details.
	Nne []NneObservation `json:"nne,omitempty" tf:"nne,omitempty"`

	// TLS posture details.
	TLS []TLSObservation `json:"tls,omitempty" tf:"tls,omitempty"`

	// Transparent data encryption posture details.
	Tde []TdeObservation `json:"tde,omitempty" tf:"tde,omitempty"`

	// Number of unencrypted backup pieces.
	UnencryptedBackupPiecesCount *float64 `json:"unencryptedBackupPiecesCount,omitempty" tf:"unencrypted_backup_pieces_count,omitempty"`
}

type CryptoPostureParameters struct {
}

type NneInitParameters struct {
}

type NneObservation struct {

	// Indicates if weak NNE options are allowed.
	AreWeakOptionsAllowed *string `json:"areWeakOptionsAllowed,omitempty" tf:"are_weak_options_allowed,omitempty"`

	// Configured network encryption algorithm.
	EncryptionConfigured []*string `json:"encryptionConfigured,omitempty" tf:"encryption_configured,omitempty"`

	// Common FIPS mode configured for the assessment when the target uses common FIPS configuration.
	FipsModeConfigured *string `json:"fipsModeConfigured,omitempty" tf:"fips_mode_configured,omitempty"`

	// NNE integrity algorithm(s).
	Integrity []*string `json:"integrity,omitempty" tf:"integrity,omitempty"`

	// Observed NNE key exchange setting.
	KeyExchange *string `json:"keyExchange,omitempty" tf:"key_exchange,omitempty"`

	// Quantum-readiness classification for NNE posture.
	QuantumReadiness *string `json:"quantumReadiness,omitempty" tf:"quantum_readiness,omitempty"`

	// Observed server-side encryption requirement.
	ServerEncryption *string `json:"serverEncryption,omitempty" tf:"server_encryption,omitempty"`

	// NNE server integrity algorithm(s).
	ServerIntegrity []*string `json:"serverIntegrity,omitempty" tf:"server_integrity,omitempty"`

	// NNE enablement status.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`
}

type NneParameters struct {
}

type TLSInitParameters struct {
}

type TLSObservation struct {

	// Indicates if weak TLS cipher suites are allowed.
	AreWeakCipherSuitesAllowed *string `json:"areWeakCipherSuitesAllowed,omitempty" tf:"are_weak_cipher_suites_allowed,omitempty"`

	// TLS cipher suites configured on target.
	CipherSuitesConfigured []*string `json:"cipherSuitesConfigured,omitempty" tf:"cipher_suites_configured,omitempty"`

	// Common FIPS mode configured for the assessment when the target uses common FIPS configuration.
	FipsModeConfigured *string `json:"fipsModeConfigured,omitempty" tf:"fips_mode_configured,omitempty"`

	// Whether TLS client authentication is configured.
	IsMtlsConfigured *string `json:"isMtlsConfigured,omitempty" tf:"is_mtls_configured,omitempty"`

	// Quantum-readiness classification for NNE posture.
	QuantumReadiness *string `json:"quantumReadiness,omitempty" tf:"quantum_readiness,omitempty"`

	// Certificate revocation checking mode.
	RevocationMode *string `json:"revocationMode,omitempty" tf:"revocation_mode,omitempty"`

	// NNE enablement status.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// TLS versions configured on target.
	Versions []*string `json:"versions,omitempty" tf:"versions,omitempty"`

	// The observed wallet location for TDE keys.
	WalletLocation *string `json:"walletLocation,omitempty" tf:"wallet_location,omitempty"`
}

type TLSParameters struct {
}

type TdeInitParameters struct {
}

type TdeObservation struct {

	// Observed DB credentials encryption algorithm.
	DBCredentialsEncryptionObserved *string `json:"dbCredentialsEncryptionObserved,omitempty" tf:"db_credentials_encryption_observed,omitempty"`

	// Number of encrypted tablespaces detected.
	EncryptedTablespacesCount *float64 `json:"encryptedTablespacesCount,omitempty" tf:"encrypted_tablespaces_count,omitempty"`

	// Configured network encryption algorithm.
	EncryptionConfigured []*string `json:"encryptionConfigured,omitempty" tf:"encryption_configured,omitempty"`

	// Common FIPS mode configured for the assessment when the target uses common FIPS configuration.
	FipsModeConfigured *string `json:"fipsModeConfigured,omitempty" tf:"fips_mode_configured,omitempty"`

	// Configured TDE integrity-related setting.
	IntegrityConfigured []*string `json:"integrityConfigured,omitempty" tf:"integrity_configured,omitempty"`

	// The observed TDE key cache status.
	KeyCacheStatus *string `json:"keyCacheStatus,omitempty" tf:"key_cache_status,omitempty"`

	// The observed TDE key store type.
	KeyStoreType *string `json:"keyStoreType,omitempty" tf:"key_store_type,omitempty"`

	// The observed encryption algorithm used by the master key.
	MasterKeyEncryptionAlgorithm *string `json:"masterKeyEncryptionAlgorithm,omitempty" tf:"master_key_encryption_algorithm,omitempty"`

	// The observed TDE master key identifier.
	MasterKeyID *string `json:"masterKeyId,omitempty" tf:"master_key_id,omitempty"`

	// Quantum-readiness classification for NNE posture.
	QuantumReadiness *string `json:"quantumReadiness,omitempty" tf:"quantum_readiness,omitempty"`

	// Observed redo log encryption algorithm.
	RedoEncryptionObserved *string `json:"redoEncryptionObserved,omitempty" tf:"redo_encryption_observed,omitempty"`

	// NNE enablement status.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// The last observed rotation time for the TDE master key, in RFC3339 format.
	TimeMasterKeyLastRotation *string `json:"timeMasterKeyLastRotation,omitempty" tf:"time_master_key_last_rotation,omitempty"`

	// Number of unencrypted tablespaces detected.
	UnencryptedTablespacesCount *float64 `json:"unencryptedTablespacesCount,omitempty" tf:"unencrypted_tablespaces_count,omitempty"`

	// The observed wallet location for TDE keys.
	WalletLocation *string `json:"walletLocation,omitempty" tf:"wallet_location,omitempty"`
}

type TdeParameters struct {
}

// CryptoAssessmentSpec defines the desired state of CryptoAssessment
type CryptoAssessmentSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            CryptoAssessmentParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider CryptoAssessmentInitParameters `json:"initProvider,omitempty"`
}

// CryptoAssessmentStatus defines the observed state of CryptoAssessment.
type CryptoAssessmentStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        CryptoAssessmentObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// CryptoAssessment is the Schema for the CryptoAssessments API. Provides the Crypto Assessment resource in Oracle Cloud Infrastructure Data Safe service
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,oci}
type CryptoAssessment struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              CryptoAssessmentSpec   `json:"spec"`
	Status            CryptoAssessmentStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CryptoAssessmentList contains a list of CryptoAssessments
type CryptoAssessmentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []CryptoAssessment `json:"items"`
}

// Repository type metadata.
var (
	CryptoAssessment_Kind             = "CryptoAssessment"
	CryptoAssessment_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: CryptoAssessment_Kind}.String()
	CryptoAssessment_KindAPIVersion   = CryptoAssessment_Kind + "." + CRDGroupVersion.String()
	CryptoAssessment_GroupVersionKind = CRDGroupVersion.WithKind(CryptoAssessment_Kind)
)

func init() {
	SchemeBuilder.Register(&CryptoAssessment{}, &CryptoAssessmentList{})
}
