/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type DatabaseSoftwareScheduleManagementInitParameters struct {

	// The database OCID.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/database/v1alpha1.Database
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	DatabaseID *string `json:"databaseId,omitempty" tf:"database_id,omitempty"`

	// Reference to a Database in database to populate databaseId.
	// +kubebuilder:validation:Optional
	DatabaseIDRef *v1.NamespacedReference `json:"databaseIdRef,omitempty" tf:"-"`

	// Selector for a Database in database to populate databaseId.
	// +kubebuilder:validation:Optional
	DatabaseIDSelector *v1.NamespacedSelector `json:"databaseIdSelector,omitempty" tf:"-"`
}

type DatabaseSoftwareScheduleManagementObservation struct {

	// The database OCID.
	DatabaseID *string `json:"databaseId,omitempty" tf:"database_id,omitempty"`

	// The OCID of the backup destination.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type DatabaseSoftwareScheduleManagementParameters struct {

	// The database OCID.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/database/v1alpha1.Database
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	DatabaseID *string `json:"databaseId,omitempty" tf:"database_id,omitempty"`

	// Reference to a Database in database to populate databaseId.
	// +kubebuilder:validation:Optional
	DatabaseIDRef *v1.NamespacedReference `json:"databaseIdRef,omitempty" tf:"-"`

	// Selector for a Database in database to populate databaseId.
	// +kubebuilder:validation:Optional
	DatabaseIDSelector *v1.NamespacedSelector `json:"databaseIdSelector,omitempty" tf:"-"`
}

// DatabaseSoftwareScheduleManagementSpec defines the desired state of DatabaseSoftwareScheduleManagement
type DatabaseSoftwareScheduleManagementSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            DatabaseSoftwareScheduleManagementParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider DatabaseSoftwareScheduleManagementInitParameters `json:"initProvider,omitempty"`
}

// DatabaseSoftwareScheduleManagementStatus defines the observed state of DatabaseSoftwareScheduleManagement.
type DatabaseSoftwareScheduleManagementStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        DatabaseSoftwareScheduleManagementObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// DatabaseSoftwareScheduleManagement is the Schema for the DatabaseSoftwareScheduleManagements API. Provides the Database Software Schedule Management resource in Oracle Cloud Infrastructure Database service
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,oci}
type DatabaseSoftwareScheduleManagement struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              DatabaseSoftwareScheduleManagementSpec   `json:"spec"`
	Status            DatabaseSoftwareScheduleManagementStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DatabaseSoftwareScheduleManagementList contains a list of DatabaseSoftwareScheduleManagements
type DatabaseSoftwareScheduleManagementList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DatabaseSoftwareScheduleManagement `json:"items"`
}

// Repository type metadata.
var (
	DatabaseSoftwareScheduleManagement_Kind             = "DatabaseSoftwareScheduleManagement"
	DatabaseSoftwareScheduleManagement_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: DatabaseSoftwareScheduleManagement_Kind}.String()
	DatabaseSoftwareScheduleManagement_KindAPIVersion   = DatabaseSoftwareScheduleManagement_Kind + "." + CRDGroupVersion.String()
	DatabaseSoftwareScheduleManagement_GroupVersionKind = CRDGroupVersion.WithKind(DatabaseSoftwareScheduleManagement_Kind)
)

func init() {
	SchemeBuilder.Register(&DatabaseSoftwareScheduleManagement{}, &DatabaseSoftwareScheduleManagementList{})
}
