/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ToolsRuntimeDatabaseToolsApiGatewayConfigPoolAutoApiSpecInitParameters struct {

	// (Updatable) Used as the URI path element for this object. When not specified the objectName lowercase is the default value.
	Alias *string `json:"alias,omitempty" tf:"alias,omitempty"`

	// (Updatable) The name of the database object.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/objectstorage/v1alpha1.Object
	DatabaseObjectName *string `json:"databaseObjectName,omitempty" tf:"database_object_name,omitempty"`

	// Reference to a Object in objectstorage to populate databaseObjectName.
	// +kubebuilder:validation:Optional
	DatabaseObjectNameRef *v1.NamespacedReference `json:"databaseObjectNameRef,omitempty" tf:"-"`

	// Selector for a Object in objectstorage to populate databaseObjectName.
	// +kubebuilder:validation:Optional
	DatabaseObjectNameSelector *v1.NamespacedSelector `json:"databaseObjectNameSelector,omitempty" tf:"-"`

	// (Updatable) The type of the database object.
	DatabaseObjectType *string `json:"databaseObjectType,omitempty" tf:"database_object_type,omitempty"`

	// The OCID of a Database Tools database API gateway config.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/apmconfig/v1alpha1.Config
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	DatabaseToolsDatabaseAPIGatewayConfigID *string `json:"databaseToolsDatabaseApiGatewayConfigId,omitempty" tf:"database_tools_database_api_gateway_config_id,omitempty"`

	// Reference to a Config in apmconfig to populate databaseToolsDatabaseApiGatewayConfigId.
	// +kubebuilder:validation:Optional
	DatabaseToolsDatabaseAPIGatewayConfigIDRef *v1.NamespacedReference `json:"databaseToolsDatabaseApiGatewayConfigIdRef,omitempty" tf:"-"`

	// Selector for a Config in apmconfig to populate databaseToolsDatabaseApiGatewayConfigId.
	// +kubebuilder:validation:Optional
	DatabaseToolsDatabaseAPIGatewayConfigIDSelector *v1.NamespacedSelector `json:"databaseToolsDatabaseApiGatewayConfigIdSelector,omitempty" tf:"-"`

	// (Updatable) Description of the autoApiSpec.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Updatable) A user-friendly name. Does not have to be unique, and it’s changeable. Avoid entering confidential information.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Updatable) The operations to limit access to this resource. If not specified then the default is ["READ","WRITE"].
	Operations []*string `json:"operations,omitempty" tf:"operations,omitempty"`

	// The key of the pool config.
	PoolKey *string `json:"poolKey,omitempty" tf:"pool_key,omitempty"`

	// (Updatable) The name of the database API gateway config roles protecting the resource. Only valid for RBAC JWT Profile pools and BEARER securitySchemes.
	Roles []*string `json:"roles,omitempty" tf:"roles,omitempty"`

	// (Updatable) The name of the database API gateway config privilege protecting the resource. Only valid for SCOPE JWT Profile pools and BEARER securitySchemes.
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`

	// (Updatable) The security schemes that can access this resource. If not specified then the resource is public.
	SecuritySchemes []*string `json:"securitySchemes,omitempty" tf:"security_schemes,omitempty"`

	// (Updatable) The type of the Database Tools database API gateway config auto API spec sub resource.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ToolsRuntimeDatabaseToolsApiGatewayConfigPoolAutoApiSpecObservation struct {

	// (Updatable) Used as the URI path element for this object. When not specified the objectName lowercase is the default value.
	Alias *string `json:"alias,omitempty" tf:"alias,omitempty"`

	// (Updatable) The name of the database object.
	DatabaseObjectName *string `json:"databaseObjectName,omitempty" tf:"database_object_name,omitempty"`

	// (Updatable) The type of the database object.
	DatabaseObjectType *string `json:"databaseObjectType,omitempty" tf:"database_object_type,omitempty"`

	// The OCID of a Database Tools database API gateway config.
	DatabaseToolsDatabaseAPIGatewayConfigID *string `json:"databaseToolsDatabaseApiGatewayConfigId,omitempty" tf:"database_tools_database_api_gateway_config_id,omitempty"`

	// (Updatable) Description of the autoApiSpec.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Updatable) A user-friendly name. Does not have to be unique, and it’s changeable. Avoid entering confidential information.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// A system generated string that uniquely identifies an auto API spec sub resource within a given pool.
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// (Updatable) The operations to limit access to this resource. If not specified then the default is ["READ","WRITE"].
	Operations []*string `json:"operations,omitempty" tf:"operations,omitempty"`

	// The key of the pool config.
	PoolKey *string `json:"poolKey,omitempty" tf:"pool_key,omitempty"`

	// (Updatable) The name of the database API gateway config roles protecting the resource. Only valid for RBAC JWT Profile pools and BEARER securitySchemes.
	Roles []*string `json:"roles,omitempty" tf:"roles,omitempty"`

	// (Updatable) The name of the database API gateway config privilege protecting the resource. Only valid for SCOPE JWT Profile pools and BEARER securitySchemes.
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`

	// (Updatable) The security schemes that can access this resource. If not specified then the resource is public.
	SecuritySchemes []*string `json:"securitySchemes,omitempty" tf:"security_schemes,omitempty"`

	// The time the resource was created. An RFC3339 formatted datetime string.
	TimeCreated *string `json:"timeCreated,omitempty" tf:"time_created,omitempty"`

	// The time the resource was updated. An RFC3339 formatted datetime string.
	TimeUpdated *string `json:"timeUpdated,omitempty" tf:"time_updated,omitempty"`

	// (Updatable) The type of the Database Tools database API gateway config auto API spec sub resource.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ToolsRuntimeDatabaseToolsApiGatewayConfigPoolAutoApiSpecParameters struct {

	// (Updatable) Used as the URI path element for this object. When not specified the objectName lowercase is the default value.
	// +kubebuilder:validation:Optional
	Alias *string `json:"alias,omitempty" tf:"alias,omitempty"`

	// (Updatable) The name of the database object.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/objectstorage/v1alpha1.Object
	// +kubebuilder:validation:Optional
	DatabaseObjectName *string `json:"databaseObjectName,omitempty" tf:"database_object_name,omitempty"`

	// Reference to a Object in objectstorage to populate databaseObjectName.
	// +kubebuilder:validation:Optional
	DatabaseObjectNameRef *v1.NamespacedReference `json:"databaseObjectNameRef,omitempty" tf:"-"`

	// Selector for a Object in objectstorage to populate databaseObjectName.
	// +kubebuilder:validation:Optional
	DatabaseObjectNameSelector *v1.NamespacedSelector `json:"databaseObjectNameSelector,omitempty" tf:"-"`

	// (Updatable) The type of the database object.
	// +kubebuilder:validation:Optional
	DatabaseObjectType *string `json:"databaseObjectType,omitempty" tf:"database_object_type,omitempty"`

	// The OCID of a Database Tools database API gateway config.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/apmconfig/v1alpha1.Config
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	DatabaseToolsDatabaseAPIGatewayConfigID *string `json:"databaseToolsDatabaseApiGatewayConfigId,omitempty" tf:"database_tools_database_api_gateway_config_id,omitempty"`

	// Reference to a Config in apmconfig to populate databaseToolsDatabaseApiGatewayConfigId.
	// +kubebuilder:validation:Optional
	DatabaseToolsDatabaseAPIGatewayConfigIDRef *v1.NamespacedReference `json:"databaseToolsDatabaseApiGatewayConfigIdRef,omitempty" tf:"-"`

	// Selector for a Config in apmconfig to populate databaseToolsDatabaseApiGatewayConfigId.
	// +kubebuilder:validation:Optional
	DatabaseToolsDatabaseAPIGatewayConfigIDSelector *v1.NamespacedSelector `json:"databaseToolsDatabaseApiGatewayConfigIdSelector,omitempty" tf:"-"`

	// (Updatable) Description of the autoApiSpec.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Updatable) A user-friendly name. Does not have to be unique, and it’s changeable. Avoid entering confidential information.
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Updatable) The operations to limit access to this resource. If not specified then the default is ["READ","WRITE"].
	// +kubebuilder:validation:Optional
	Operations []*string `json:"operations,omitempty" tf:"operations,omitempty"`

	// The key of the pool config.
	// +kubebuilder:validation:Optional
	PoolKey *string `json:"poolKey,omitempty" tf:"pool_key,omitempty"`

	// (Updatable) The name of the database API gateway config roles protecting the resource. Only valid for RBAC JWT Profile pools and BEARER securitySchemes.
	// +kubebuilder:validation:Optional
	Roles []*string `json:"roles,omitempty" tf:"roles,omitempty"`

	// (Updatable) The name of the database API gateway config privilege protecting the resource. Only valid for SCOPE JWT Profile pools and BEARER securitySchemes.
	// +kubebuilder:validation:Optional
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`

	// (Updatable) The security schemes that can access this resource. If not specified then the resource is public.
	// +kubebuilder:validation:Optional
	SecuritySchemes []*string `json:"securitySchemes,omitempty" tf:"security_schemes,omitempty"`

	// (Updatable) The type of the Database Tools database API gateway config auto API spec sub resource.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

// ToolsRuntimeDatabaseToolsApiGatewayConfigPoolAutoApiSpecSpec defines the desired state of ToolsRuntimeDatabaseToolsApiGatewayConfigPoolAutoApiSpec
type ToolsRuntimeDatabaseToolsApiGatewayConfigPoolAutoApiSpecSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ToolsRuntimeDatabaseToolsApiGatewayConfigPoolAutoApiSpecParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ToolsRuntimeDatabaseToolsApiGatewayConfigPoolAutoApiSpecInitParameters `json:"initProvider,omitempty"`
}

// ToolsRuntimeDatabaseToolsApiGatewayConfigPoolAutoApiSpecStatus defines the observed state of ToolsRuntimeDatabaseToolsApiGatewayConfigPoolAutoApiSpec.
type ToolsRuntimeDatabaseToolsApiGatewayConfigPoolAutoApiSpecStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ToolsRuntimeDatabaseToolsApiGatewayConfigPoolAutoApiSpecObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ToolsRuntimeDatabaseToolsApiGatewayConfigPoolAutoApiSpec is the Schema for the ToolsRuntimeDatabaseToolsApiGatewayConfigPoolAutoApiSpecs API. Provides the Database Tools Database Api Gateway Config Pool Auto Api Spec resource in Oracle Cloud Infrastructure Database Tools Runtime service
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,oci}
type ToolsRuntimeDatabaseToolsApiGatewayConfigPoolAutoApiSpec struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.databaseObjectType) || (has(self.initProvider) && has(self.initProvider.databaseObjectType))",message="spec.forProvider.databaseObjectType is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.displayName) || (has(self.initProvider) && has(self.initProvider.displayName))",message="spec.forProvider.displayName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.poolKey) || (has(self.initProvider) && has(self.initProvider.poolKey))",message="spec.forProvider.poolKey is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.type) || (has(self.initProvider) && has(self.initProvider.type))",message="spec.forProvider.type is a required parameter"
	Spec   ToolsRuntimeDatabaseToolsApiGatewayConfigPoolAutoApiSpecSpec   `json:"spec"`
	Status ToolsRuntimeDatabaseToolsApiGatewayConfigPoolAutoApiSpecStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ToolsRuntimeDatabaseToolsApiGatewayConfigPoolAutoApiSpecList contains a list of ToolsRuntimeDatabaseToolsApiGatewayConfigPoolAutoApiSpecs
type ToolsRuntimeDatabaseToolsApiGatewayConfigPoolAutoApiSpecList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ToolsRuntimeDatabaseToolsApiGatewayConfigPoolAutoApiSpec `json:"items"`
}

// Repository type metadata.
var (
	ToolsRuntimeDatabaseToolsApiGatewayConfigPoolAutoApiSpec_Kind             = "ToolsRuntimeDatabaseToolsApiGatewayConfigPoolAutoApiSpec"
	ToolsRuntimeDatabaseToolsApiGatewayConfigPoolAutoApiSpec_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ToolsRuntimeDatabaseToolsApiGatewayConfigPoolAutoApiSpec_Kind}.String()
	ToolsRuntimeDatabaseToolsApiGatewayConfigPoolAutoApiSpec_KindAPIVersion   = ToolsRuntimeDatabaseToolsApiGatewayConfigPoolAutoApiSpec_Kind + "." + CRDGroupVersion.String()
	ToolsRuntimeDatabaseToolsApiGatewayConfigPoolAutoApiSpec_GroupVersionKind = CRDGroupVersion.WithKind(ToolsRuntimeDatabaseToolsApiGatewayConfigPoolAutoApiSpec_Kind)
)

func init() {
	SchemeBuilder.Register(&ToolsRuntimeDatabaseToolsApiGatewayConfigPoolAutoApiSpec{}, &ToolsRuntimeDatabaseToolsApiGatewayConfigPoolAutoApiSpecList{})
}
