/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ToolsRuntimeDatabaseToolsApiGatewayConfigPoolApiSpecInitParameters struct {

	// (Updatable) The content of a string-escaped Open API spec in JSON format.
	Content *string `json:"content,omitempty" tf:"content,omitempty"`

	// The OCID of a Database Tools database API gateway config.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/apmconfig/v1alpha1.Config
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	DatabaseToolsDatabaseAPIGatewayConfigID *string `json:"databaseToolsDatabaseApiGatewayConfigId,omitempty" tf:"database_tools_database_api_gateway_config_id,omitempty"`

	// Reference to a Config in apmconfig to populate databaseToolsDatabaseApiGatewayConfigId.
	// +kubebuilder:validation:Optional
	DatabaseToolsDatabaseAPIGatewayConfigIDRef *v1.NamespacedReference `json:"databaseToolsDatabaseApiGatewayConfigIdRef,omitempty" tf:"-"`

	// Selector for a Config in apmconfig to populate databaseToolsDatabaseApiGatewayConfigId.
	// +kubebuilder:validation:Optional
	DatabaseToolsDatabaseAPIGatewayConfigIDSelector *v1.NamespacedSelector `json:"databaseToolsDatabaseApiGatewayConfigIdSelector,omitempty" tf:"-"`

	// (Updatable) A user-friendly name. Does not have to be unique, and it’s changeable. Avoid entering confidential information.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// The key of the pool config.
	PoolKey *string `json:"poolKey,omitempty" tf:"pool_key,omitempty"`

	// (Updatable) The type of the Database Tools database API gateway config API spec sub resource.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ToolsRuntimeDatabaseToolsApiGatewayConfigPoolApiSpecObservation struct {

	// (Updatable) The content of a string-escaped Open API spec in JSON format.
	Content *string `json:"content,omitempty" tf:"content,omitempty"`

	// The OCID of a Database Tools database API gateway config.
	DatabaseToolsDatabaseAPIGatewayConfigID *string `json:"databaseToolsDatabaseApiGatewayConfigId,omitempty" tf:"database_tools_database_api_gateway_config_id,omitempty"`

	// (Updatable) A user-friendly name. Does not have to be unique, and it’s changeable. Avoid entering confidential information.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// A system generated string that uniquely identifies an API spec sub resource within a given pool.
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// The key of the pool config.
	PoolKey *string `json:"poolKey,omitempty" tf:"pool_key,omitempty"`

	// The time the resource was created. An RFC3339 formatted datetime string.
	TimeCreated *string `json:"timeCreated,omitempty" tf:"time_created,omitempty"`

	// The time the resource was updated. An RFC3339 formatted datetime string.
	TimeUpdated *string `json:"timeUpdated,omitempty" tf:"time_updated,omitempty"`

	// (Updatable) The type of the Database Tools database API gateway config API spec sub resource.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ToolsRuntimeDatabaseToolsApiGatewayConfigPoolApiSpecParameters struct {

	// (Updatable) The content of a string-escaped Open API spec in JSON format.
	// +kubebuilder:validation:Optional
	Content *string `json:"content,omitempty" tf:"content,omitempty"`

	// The OCID of a Database Tools database API gateway config.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/apmconfig/v1alpha1.Config
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	DatabaseToolsDatabaseAPIGatewayConfigID *string `json:"databaseToolsDatabaseApiGatewayConfigId,omitempty" tf:"database_tools_database_api_gateway_config_id,omitempty"`

	// Reference to a Config in apmconfig to populate databaseToolsDatabaseApiGatewayConfigId.
	// +kubebuilder:validation:Optional
	DatabaseToolsDatabaseAPIGatewayConfigIDRef *v1.NamespacedReference `json:"databaseToolsDatabaseApiGatewayConfigIdRef,omitempty" tf:"-"`

	// Selector for a Config in apmconfig to populate databaseToolsDatabaseApiGatewayConfigId.
	// +kubebuilder:validation:Optional
	DatabaseToolsDatabaseAPIGatewayConfigIDSelector *v1.NamespacedSelector `json:"databaseToolsDatabaseApiGatewayConfigIdSelector,omitempty" tf:"-"`

	// (Updatable) A user-friendly name. Does not have to be unique, and it’s changeable. Avoid entering confidential information.
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// The key of the pool config.
	// +kubebuilder:validation:Optional
	PoolKey *string `json:"poolKey,omitempty" tf:"pool_key,omitempty"`

	// (Updatable) The type of the Database Tools database API gateway config API spec sub resource.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

// ToolsRuntimeDatabaseToolsApiGatewayConfigPoolApiSpecSpec defines the desired state of ToolsRuntimeDatabaseToolsApiGatewayConfigPoolApiSpec
type ToolsRuntimeDatabaseToolsApiGatewayConfigPoolApiSpecSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ToolsRuntimeDatabaseToolsApiGatewayConfigPoolApiSpecParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ToolsRuntimeDatabaseToolsApiGatewayConfigPoolApiSpecInitParameters `json:"initProvider,omitempty"`
}

// ToolsRuntimeDatabaseToolsApiGatewayConfigPoolApiSpecStatus defines the observed state of ToolsRuntimeDatabaseToolsApiGatewayConfigPoolApiSpec.
type ToolsRuntimeDatabaseToolsApiGatewayConfigPoolApiSpecStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ToolsRuntimeDatabaseToolsApiGatewayConfigPoolApiSpecObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ToolsRuntimeDatabaseToolsApiGatewayConfigPoolApiSpec is the Schema for the ToolsRuntimeDatabaseToolsApiGatewayConfigPoolApiSpecs API. Provides the Database Tools Database Api Gateway Config Pool Api Spec resource in Oracle Cloud Infrastructure Database Tools Runtime service
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,oci}
type ToolsRuntimeDatabaseToolsApiGatewayConfigPoolApiSpec struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.content) || (has(self.initProvider) && has(self.initProvider.content))",message="spec.forProvider.content is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.displayName) || (has(self.initProvider) && has(self.initProvider.displayName))",message="spec.forProvider.displayName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.poolKey) || (has(self.initProvider) && has(self.initProvider.poolKey))",message="spec.forProvider.poolKey is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.type) || (has(self.initProvider) && has(self.initProvider.type))",message="spec.forProvider.type is a required parameter"
	Spec   ToolsRuntimeDatabaseToolsApiGatewayConfigPoolApiSpecSpec   `json:"spec"`
	Status ToolsRuntimeDatabaseToolsApiGatewayConfigPoolApiSpecStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ToolsRuntimeDatabaseToolsApiGatewayConfigPoolApiSpecList contains a list of ToolsRuntimeDatabaseToolsApiGatewayConfigPoolApiSpecs
type ToolsRuntimeDatabaseToolsApiGatewayConfigPoolApiSpecList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ToolsRuntimeDatabaseToolsApiGatewayConfigPoolApiSpec `json:"items"`
}

// Repository type metadata.
var (
	ToolsRuntimeDatabaseToolsApiGatewayConfigPoolApiSpec_Kind             = "ToolsRuntimeDatabaseToolsApiGatewayConfigPoolApiSpec"
	ToolsRuntimeDatabaseToolsApiGatewayConfigPoolApiSpec_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ToolsRuntimeDatabaseToolsApiGatewayConfigPoolApiSpec_Kind}.String()
	ToolsRuntimeDatabaseToolsApiGatewayConfigPoolApiSpec_KindAPIVersion   = ToolsRuntimeDatabaseToolsApiGatewayConfigPoolApiSpec_Kind + "." + CRDGroupVersion.String()
	ToolsRuntimeDatabaseToolsApiGatewayConfigPoolApiSpec_GroupVersionKind = CRDGroupVersion.WithKind(ToolsRuntimeDatabaseToolsApiGatewayConfigPoolApiSpec_Kind)
)

func init() {
	SchemeBuilder.Register(&ToolsRuntimeDatabaseToolsApiGatewayConfigPoolApiSpec{}, &ToolsRuntimeDatabaseToolsApiGatewayConfigPoolApiSpecList{})
}
