/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type KafkaClusterAddonInitParameters struct {

	// (Updatable) This is Addon Type of Oracle Cloud Infrastructure kafka cluster
	AddonType *string `json:"addonType,omitempty" tf:"addon_type,omitempty"`

	// Authentication mechanism.
	AuthenticationMechanism *string `json:"authenticationMechanism,omitempty" tf:"authentication_mechanism,omitempty"`

	// (Updatable) A brief description of the add on being installed.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The OCID of the KafkaCluster.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/cluster/managedkafka/v1alpha1.KafkaCluster
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	KafkaClusterID *string `json:"kafkaClusterId,omitempty" tf:"kafka_cluster_id,omitempty"`

	// Reference to a KafkaCluster in managedkafka to populate kafkaClusterId.
	// +kubebuilder:validation:Optional
	KafkaClusterIDRef *v1.Reference `json:"kafkaClusterIdRef,omitempty" tf:"-"`

	// Selector for a KafkaCluster in managedkafka to populate kafkaClusterId.
	// +kubebuilder:validation:Optional
	KafkaClusterIDSelector *v1.Selector `json:"kafkaClusterIdSelector,omitempty" tf:"-"`

	// A unique user-friendly name. Avoid entering confidential information.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Updatable) A list of CIDR's for ingress/egress traffic.
	NetworkCidrs []*string `json:"networkCidrs,omitempty" tf:"network_cidrs,omitempty"`
}

type KafkaClusterAddonObservation struct {

	// (Updatable) This is Addon Type of Oracle Cloud Infrastructure kafka cluster
	AddonType *string `json:"addonType,omitempty" tf:"addon_type,omitempty"`

	// Authentication mechanism.
	AuthenticationMechanism *string `json:"authenticationMechanism,omitempty" tf:"authentication_mechanism,omitempty"`

	// The bootstrap url of the kafka cluster.
	BootstrapURL *string `json:"bootstrapUrl,omitempty" tf:"bootstrap_url,omitempty"`

	// (Updatable) A brief description of the add on being installed.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The OCID of the KafkaCluster.
	KafkaClusterID *string `json:"kafkaClusterId,omitempty" tf:"kafka_cluster_id,omitempty"`

	// A unique user-friendly name. Avoid entering confidential information.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Updatable) A list of CIDR's for ingress/egress traffic.
	NetworkCidrs []*string `json:"networkCidrs,omitempty" tf:"network_cidrs,omitempty"`

	// The current state of the KafkaCluster.
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// The time the addon was created.
	TimeCreated *string `json:"timeCreated,omitempty" tf:"time_created,omitempty"`

	// The time the addon was updated.
	TimeUpdated *string `json:"timeUpdated,omitempty" tf:"time_updated,omitempty"`
}

type KafkaClusterAddonParameters struct {

	// (Updatable) This is Addon Type of Oracle Cloud Infrastructure kafka cluster
	// +kubebuilder:validation:Optional
	AddonType *string `json:"addonType,omitempty" tf:"addon_type,omitempty"`

	// Authentication mechanism.
	// +kubebuilder:validation:Optional
	AuthenticationMechanism *string `json:"authenticationMechanism,omitempty" tf:"authentication_mechanism,omitempty"`

	// (Updatable) A brief description of the add on being installed.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The OCID of the KafkaCluster.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/cluster/managedkafka/v1alpha1.KafkaCluster
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	KafkaClusterID *string `json:"kafkaClusterId,omitempty" tf:"kafka_cluster_id,omitempty"`

	// Reference to a KafkaCluster in managedkafka to populate kafkaClusterId.
	// +kubebuilder:validation:Optional
	KafkaClusterIDRef *v1.Reference `json:"kafkaClusterIdRef,omitempty" tf:"-"`

	// Selector for a KafkaCluster in managedkafka to populate kafkaClusterId.
	// +kubebuilder:validation:Optional
	KafkaClusterIDSelector *v1.Selector `json:"kafkaClusterIdSelector,omitempty" tf:"-"`

	// A unique user-friendly name. Avoid entering confidential information.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Updatable) A list of CIDR's for ingress/egress traffic.
	// +kubebuilder:validation:Optional
	NetworkCidrs []*string `json:"networkCidrs,omitempty" tf:"network_cidrs,omitempty"`
}

// KafkaClusterAddonSpec defines the desired state of KafkaClusterAddon
type KafkaClusterAddonSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     KafkaClusterAddonParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider KafkaClusterAddonInitParameters `json:"initProvider,omitempty"`
}

// KafkaClusterAddonStatus defines the observed state of KafkaClusterAddon.
type KafkaClusterAddonStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        KafkaClusterAddonObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// KafkaClusterAddon is the Schema for the KafkaClusterAddons API. Provides the Kafka Cluster Addon resource in Oracle Cloud Infrastructure Managed Kafka service
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,oci}
type KafkaClusterAddon struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.addonType) || (has(self.initProvider) && has(self.initProvider.addonType))",message="spec.forProvider.addonType is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.authenticationMechanism) || (has(self.initProvider) && has(self.initProvider.authenticationMechanism))",message="spec.forProvider.authenticationMechanism is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.networkCidrs) || (has(self.initProvider) && has(self.initProvider.networkCidrs))",message="spec.forProvider.networkCidrs is a required parameter"
	Spec   KafkaClusterAddonSpec   `json:"spec"`
	Status KafkaClusterAddonStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// KafkaClusterAddonList contains a list of KafkaClusterAddons
type KafkaClusterAddonList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []KafkaClusterAddon `json:"items"`
}

// Repository type metadata.
var (
	KafkaClusterAddon_Kind             = "KafkaClusterAddon"
	KafkaClusterAddon_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: KafkaClusterAddon_Kind}.String()
	KafkaClusterAddon_KindAPIVersion   = KafkaClusterAddon_Kind + "." + CRDGroupVersion.String()
	KafkaClusterAddon_GroupVersionKind = CRDGroupVersion.WithKind(KafkaClusterAddon_Kind)
)

func init() {
	SchemeBuilder.Register(&KafkaClusterAddon{}, &KafkaClusterAddonList{})
}
