/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type BdsInstanceBdsCertificateConfigurationInitParameters struct {

	// The OCID of the cluster.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/cluster/bds/v1alpha1.BdsInstance
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	BdsInstanceID *string `json:"bdsInstanceId,omitempty" tf:"bds_instance_id,omitempty"`

	// Reference to a BdsInstance in bds to populate bdsInstanceId.
	// +kubebuilder:validation:Optional
	BdsInstanceIDRef *v1.Reference `json:"bdsInstanceIdRef,omitempty" tf:"-"`

	// Selector for a BdsInstance in bds to populate bdsInstanceId.
	// +kubebuilder:validation:Optional
	BdsInstanceIDSelector *v1.Selector `json:"bdsInstanceIdSelector,omitempty" tf:"-"`

	// The OCID of the certificate authority which is associated with this certificate configuration.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/cluster/certificatesmanagement/v1alpha1.CertificateAuthority
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	CertificateAuthorityID *string `json:"certificateAuthorityId,omitempty" tf:"certificate_authority_id,omitempty"`

	// Reference to a CertificateAuthority in certificatesmanagement to populate certificateAuthorityId.
	// +kubebuilder:validation:Optional
	CertificateAuthorityIDRef *v1.Reference `json:"certificateAuthorityIdRef,omitempty" tf:"-"`

	// Selector for a CertificateAuthority in certificatesmanagement to populate certificateAuthorityId.
	// +kubebuilder:validation:Optional
	CertificateAuthorityIDSelector *v1.Selector `json:"certificateAuthorityIdSelector,omitempty" tf:"-"`

	// The type of the BDS certificate configuration, also the type of the BDS certificates which will be generated by the BDS certificate configuration.
	CertificateType *string `json:"certificateType,omitempty" tf:"certificate_type,omitempty"`

	// Base64-encoded cluster admin password used for issue, renew, or set default actions. Use this or secret_id.
	ClusterAdminPasswordSecretRef *v1.SecretKeySelector `json:"clusterAdminPasswordSecretRef,omitempty" tf:"-"`

	// The OCID of the compartment of the certificate authority connecting to this certificate configuration.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/cluster/identity/v1alpha1.Compartment
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// Reference to a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDRef *v1.Reference `json:"compartmentIdRef,omitempty" tf:"-"`

	// Selector for a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDSelector *v1.Selector `json:"compartmentIdSelector,omitempty" tf:"-"`

	// The display name of the BDS certificate configuration.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// When issuing certificates for the configuration, limits generation to nodes that do not yet have the configuration.
	IsMissingNodesOnly *bool `json:"isMissingNodesOnly,omitempty" tf:"is_missing_nodes_only,omitempty"`

	// invokes certificate generation for the configuration
	IssueCertificateTrigger *string `json:"issueCertificateTrigger,omitempty" tf:"issue_certificate_trigger,omitempty"`

	// invokes certificate renewal for the configuration
	RenewCertificateTrigger *string `json:"renewCertificateTrigger,omitempty" tf:"renew_certificate_trigger,omitempty"`

	// The OCID of the secret containing the cluster admin password used for issue, renew, or set default actions. Use this or cluster_admin_password.
	SecretID *string `json:"secretId,omitempty" tf:"secret_id,omitempty"`

	// marks the configuration as the cluster default
	SetDefaultTrigger *string `json:"setDefaultTrigger,omitempty" tf:"set_default_trigger,omitempty"`
}

type BdsInstanceBdsCertificateConfigurationObservation struct {

	// The OCID of the cluster.
	BdsInstanceID *string `json:"bdsInstanceId,omitempty" tf:"bds_instance_id,omitempty"`

	// The OCID of the certificate authority which is associated with this certificate configuration.
	CertificateAuthorityID *string `json:"certificateAuthorityId,omitempty" tf:"certificate_authority_id,omitempty"`

	// The type of the BDS certificate configuration, also the type of the BDS certificates which will be generated by the BDS certificate configuration.
	CertificateType *string `json:"certificateType,omitempty" tf:"certificate_type,omitempty"`

	// The OCID of the compartment of the certificate authority connecting to this certificate configuration.
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// The display name of the BDS certificate configuration.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// The ID of the BDS certificate configuration defined under BDS resources, not OCID.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// If this BDS certificate configuration is a default configuration or not. There will be only one Default certificate configuration per BDS cluster.
	IsDefaultConfiguration *bool `json:"isDefaultConfiguration,omitempty" tf:"is_default_configuration,omitempty"`

	// When issuing certificates for the configuration, limits generation to nodes that do not yet have the configuration.
	IsMissingNodesOnly *bool `json:"isMissingNodesOnly,omitempty" tf:"is_missing_nodes_only,omitempty"`

	// invokes certificate generation for the configuration
	IssueCertificateTrigger *string `json:"issueCertificateTrigger,omitempty" tf:"issue_certificate_trigger,omitempty"`

	// invokes certificate renewal for the configuration
	RenewCertificateTrigger *string `json:"renewCertificateTrigger,omitempty" tf:"renew_certificate_trigger,omitempty"`

	// The OCID of the secret containing the cluster admin password used for issue, renew, or set default actions. Use this or cluster_admin_password.
	SecretID *string `json:"secretId,omitempty" tf:"secret_id,omitempty"`

	// marks the configuration as the cluster default
	SetDefaultTrigger *string `json:"setDefaultTrigger,omitempty" tf:"set_default_trigger,omitempty"`

	// The lifecycle status of the BDS certificate configuration.
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// The time when the BDS certificate configuration was created, shown as an RFC 3339 formatted datetime string.
	TimeCreated *string `json:"timeCreated,omitempty" tf:"time_created,omitempty"`

	// The last time the BDS certificate configuration was used to generate or renew the certificate(s).
	TimeLastRefreshedOrGenerated *string `json:"timeLastRefreshedOrGenerated,omitempty" tf:"time_last_refreshed_or_generated,omitempty"`

	// The time the BDS certificate configuration was updated, shown as an RFC 3339 formatted datetime string.
	TimeUpdated *string `json:"timeUpdated,omitempty" tf:"time_updated,omitempty"`

	// The type of the BDS certificate configuration, also the type of the BDS certificates which will be generated by the BDS certificate configuration.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type BdsInstanceBdsCertificateConfigurationParameters struct {

	// The OCID of the cluster.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/cluster/bds/v1alpha1.BdsInstance
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	BdsInstanceID *string `json:"bdsInstanceId,omitempty" tf:"bds_instance_id,omitempty"`

	// Reference to a BdsInstance in bds to populate bdsInstanceId.
	// +kubebuilder:validation:Optional
	BdsInstanceIDRef *v1.Reference `json:"bdsInstanceIdRef,omitempty" tf:"-"`

	// Selector for a BdsInstance in bds to populate bdsInstanceId.
	// +kubebuilder:validation:Optional
	BdsInstanceIDSelector *v1.Selector `json:"bdsInstanceIdSelector,omitempty" tf:"-"`

	// The OCID of the certificate authority which is associated with this certificate configuration.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/cluster/certificatesmanagement/v1alpha1.CertificateAuthority
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	CertificateAuthorityID *string `json:"certificateAuthorityId,omitempty" tf:"certificate_authority_id,omitempty"`

	// Reference to a CertificateAuthority in certificatesmanagement to populate certificateAuthorityId.
	// +kubebuilder:validation:Optional
	CertificateAuthorityIDRef *v1.Reference `json:"certificateAuthorityIdRef,omitempty" tf:"-"`

	// Selector for a CertificateAuthority in certificatesmanagement to populate certificateAuthorityId.
	// +kubebuilder:validation:Optional
	CertificateAuthorityIDSelector *v1.Selector `json:"certificateAuthorityIdSelector,omitempty" tf:"-"`

	// The type of the BDS certificate configuration, also the type of the BDS certificates which will be generated by the BDS certificate configuration.
	// +kubebuilder:validation:Optional
	CertificateType *string `json:"certificateType,omitempty" tf:"certificate_type,omitempty"`

	// Base64-encoded cluster admin password used for issue, renew, or set default actions. Use this or secret_id.
	// +kubebuilder:validation:Optional
	ClusterAdminPasswordSecretRef *v1.SecretKeySelector `json:"clusterAdminPasswordSecretRef,omitempty" tf:"-"`

	// The OCID of the compartment of the certificate authority connecting to this certificate configuration.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/cluster/identity/v1alpha1.Compartment
	// +kubebuilder:validation:Optional
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// Reference to a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDRef *v1.Reference `json:"compartmentIdRef,omitempty" tf:"-"`

	// Selector for a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDSelector *v1.Selector `json:"compartmentIdSelector,omitempty" tf:"-"`

	// The display name of the BDS certificate configuration.
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// When issuing certificates for the configuration, limits generation to nodes that do not yet have the configuration.
	// +kubebuilder:validation:Optional
	IsMissingNodesOnly *bool `json:"isMissingNodesOnly,omitempty" tf:"is_missing_nodes_only,omitempty"`

	// invokes certificate generation for the configuration
	// +kubebuilder:validation:Optional
	IssueCertificateTrigger *string `json:"issueCertificateTrigger,omitempty" tf:"issue_certificate_trigger,omitempty"`

	// invokes certificate renewal for the configuration
	// +kubebuilder:validation:Optional
	RenewCertificateTrigger *string `json:"renewCertificateTrigger,omitempty" tf:"renew_certificate_trigger,omitempty"`

	// The OCID of the secret containing the cluster admin password used for issue, renew, or set default actions. Use this or cluster_admin_password.
	// +kubebuilder:validation:Optional
	SecretID *string `json:"secretId,omitempty" tf:"secret_id,omitempty"`

	// marks the configuration as the cluster default
	// +kubebuilder:validation:Optional
	SetDefaultTrigger *string `json:"setDefaultTrigger,omitempty" tf:"set_default_trigger,omitempty"`
}

// BdsInstanceBdsCertificateConfigurationSpec defines the desired state of BdsInstanceBdsCertificateConfiguration
type BdsInstanceBdsCertificateConfigurationSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     BdsInstanceBdsCertificateConfigurationParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider BdsInstanceBdsCertificateConfigurationInitParameters `json:"initProvider,omitempty"`
}

// BdsInstanceBdsCertificateConfigurationStatus defines the observed state of BdsInstanceBdsCertificateConfiguration.
type BdsInstanceBdsCertificateConfigurationStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        BdsInstanceBdsCertificateConfigurationObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// BdsInstanceBdsCertificateConfiguration is the Schema for the BdsInstanceBdsCertificateConfigurations API. Provides the Bds Instance Bds Certificate Configuration resource in Oracle Cloud Infrastructure Big Data Service service
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,oci}
type BdsInstanceBdsCertificateConfiguration struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.certificateType) || (has(self.initProvider) && has(self.initProvider.certificateType))",message="spec.forProvider.certificateType is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.displayName) || (has(self.initProvider) && has(self.initProvider.displayName))",message="spec.forProvider.displayName is a required parameter"
	Spec   BdsInstanceBdsCertificateConfigurationSpec   `json:"spec"`
	Status BdsInstanceBdsCertificateConfigurationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// BdsInstanceBdsCertificateConfigurationList contains a list of BdsInstanceBdsCertificateConfigurations
type BdsInstanceBdsCertificateConfigurationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []BdsInstanceBdsCertificateConfiguration `json:"items"`
}

// Repository type metadata.
var (
	BdsInstanceBdsCertificateConfiguration_Kind             = "BdsInstanceBdsCertificateConfiguration"
	BdsInstanceBdsCertificateConfiguration_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: BdsInstanceBdsCertificateConfiguration_Kind}.String()
	BdsInstanceBdsCertificateConfiguration_KindAPIVersion   = BdsInstanceBdsCertificateConfiguration_Kind + "." + CRDGroupVersion.String()
	BdsInstanceBdsCertificateConfiguration_GroupVersionKind = CRDGroupVersion.WithKind(BdsInstanceBdsCertificateConfiguration_Kind)
)

func init() {
	SchemeBuilder.Register(&BdsInstanceBdsCertificateConfiguration{}, &BdsInstanceBdsCertificateConfigurationList{})
}
