apiVersion: database.oci.upbound.io/v1alpha1
kind: DatabaseSoftwareScheduleManagement
metadata:
  annotations:
    meta.upbound.io/example-id: database/v1alpha1/databasesoftwareschedulemanagement
  labels:
    testing.upbound.io/example-name: test_database_software_schedule_management
  name: test-database-software-schedule-management
spec:
  forProvider:
    databaseIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_database
