/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ModelRoutingPolicyInitParameters struct {

	// (Updatable) The ordered list of model names the routing candidate is selected from (for example, meta.llama-3-70b-instruct).
	AllowedModels []*string `json:"allowedModels,omitempty" tf:"allowed_models,omitempty"`
}

type ModelRoutingPolicyObservation struct {

	// (Updatable) The ordered list of model names the routing candidate is selected from (for example, meta.llama-3-70b-instruct).
	AllowedModels []*string `json:"allowedModels,omitempty" tf:"allowed_models,omitempty"`
}

type ModelRoutingPolicyParameters struct {

	// (Updatable) The ordered list of model names the routing candidate is selected from (for example, meta.llama-3-70b-instruct).
	// +kubebuilder:validation:Optional
	AllowedModels []*string `json:"allowedModels,omitempty" tf:"allowed_models,omitempty"`
}

type PreviousStateInitParameters struct {
}

type PreviousStateModelRoutingPolicyInitParameters struct {
}

type PreviousStateModelRoutingPolicyObservation struct {

	// (Updatable) The ordered list of model names the routing candidate is selected from (for example, meta.llama-3-70b-instruct).
	AllowedModels []*string `json:"allowedModels,omitempty" tf:"allowed_models,omitempty"`
}

type PreviousStateModelRoutingPolicyParameters struct {
}

type PreviousStateObservation struct {

	// (Updatable) The OCID of the compartment in which to create the routing profile.
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see Resource Tags.  Example: {"Operations.CostCenter": "42"}
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// (Updatable) An optional description of the routing profile.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Updatable) A user-friendly name. Does not have to be unique, and it's changeable.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Updatable) Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace. For more information, see Resource Tags.  Example: {"Department": "Finance"}
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	// An OCID that uniquely identifies this routing profile resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// A message describing the current state of the routing profile in more detail that can provide actionable information.
	LifecycleDetails *string `json:"lifecycleDetails,omitempty" tf:"lifecycle_details,omitempty"`

	// (Updatable) The model routing policy for the routing profile. Routing candidates are selected from the allowed models list.
	ModelRoutingPolicy []PreviousStateModelRoutingPolicyObservation `json:"modelRoutingPolicy,omitempty" tf:"model_routing_policy,omitempty"`

	// (Updatable) The cross-region routing policy for the routing profile. If this policy is not specified, only the local region is allowed.
	RegionRoutingPolicy []RegionRoutingPolicyObservation `json:"regionRoutingPolicy,omitempty" tf:"region_routing_policy,omitempty"`

	// The current state of the routing profile.
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// System tags for this resource. Each key is predefined and scoped to a namespace.  Example: {"orcl-cloud.free-tier-retained": "true"}
	// +mapType=granular
	SystemTags map[string]*string `json:"systemTags,omitempty" tf:"system_tags,omitempty"`

	// The date and time that the routing profile was created in the format of an RFC3339 datetime string.
	TimeCreated *string `json:"timeCreated,omitempty" tf:"time_created,omitempty"`

	// The date and time that the routing profile was updated in the format of an RFC3339 datetime string.
	TimeUpdated *string `json:"timeUpdated,omitempty" tf:"time_updated,omitempty"`
}

type PreviousStateParameters struct {
}

type RegionRoutingPolicyInitParameters struct {
}

type RegionRoutingPolicyObservation struct {

	// (Updatable) The ordered list of regions that routing is allowed to reach. Each entry is a region identifier (for example, us-chicago-1).
	AllowedRegions []*string `json:"allowedRegions,omitempty" tf:"allowed_regions,omitempty"`
}

type RegionRoutingPolicyParameters struct {
}

type RoutingProfileInitParameters struct {

	// (Updatable) The OCID of the compartment in which to create the routing profile.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/identity/v1alpha1.Compartment
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// Reference to a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDRef *v1.NamespacedReference `json:"compartmentIdRef,omitempty" tf:"-"`

	// Selector for a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDSelector *v1.NamespacedSelector `json:"compartmentIdSelector,omitempty" tf:"-"`

	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see Resource Tags.  Example: {"Operations.CostCenter": "42"}
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// (Updatable) An optional description of the routing profile.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Updatable) A user-friendly name. Does not have to be unique, and it's changeable.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Updatable) Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace. For more information, see Resource Tags.  Example: {"Department": "Finance"}
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	// (Updatable) The model routing policy for the routing profile. Routing candidates are selected from the allowed models list.
	ModelRoutingPolicy []ModelRoutingPolicyInitParameters `json:"modelRoutingPolicy,omitempty" tf:"model_routing_policy,omitempty"`

	// (Updatable) The cross-region routing policy for the routing profile. If this policy is not specified, only the local region is allowed.
	RegionRoutingPolicy []RoutingProfileRegionRoutingPolicyInitParameters `json:"regionRoutingPolicy,omitempty" tf:"region_routing_policy,omitempty"`
}

type RoutingProfileObservation struct {

	// (Updatable) The OCID of the compartment in which to create the routing profile.
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see Resource Tags.  Example: {"Operations.CostCenter": "42"}
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// (Updatable) An optional description of the routing profile.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Updatable) A user-friendly name. Does not have to be unique, and it's changeable.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Updatable) Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace. For more information, see Resource Tags.  Example: {"Department": "Finance"}
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	// An OCID that uniquely identifies this routing profile resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// A message describing the current state of the routing profile in more detail that can provide actionable information.
	LifecycleDetails *string `json:"lifecycleDetails,omitempty" tf:"lifecycle_details,omitempty"`

	// (Updatable) The model routing policy for the routing profile. Routing candidates are selected from the allowed models list.
	ModelRoutingPolicy []ModelRoutingPolicyObservation `json:"modelRoutingPolicy,omitempty" tf:"model_routing_policy,omitempty"`

	// A bounded snapshot of the previous state of a routing profile. This object intentionally omits previousState to avoid recursive nesting.
	PreviousState []PreviousStateObservation `json:"previousState,omitempty" tf:"previous_state,omitempty"`

	// (Updatable) The cross-region routing policy for the routing profile. If this policy is not specified, only the local region is allowed.
	RegionRoutingPolicy []RoutingProfileRegionRoutingPolicyObservation `json:"regionRoutingPolicy,omitempty" tf:"region_routing_policy,omitempty"`

	// The current state of the routing profile.
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// System tags for this resource. Each key is predefined and scoped to a namespace.  Example: {"orcl-cloud.free-tier-retained": "true"}
	// +mapType=granular
	SystemTags map[string]*string `json:"systemTags,omitempty" tf:"system_tags,omitempty"`

	// The date and time that the routing profile was created in the format of an RFC3339 datetime string.
	TimeCreated *string `json:"timeCreated,omitempty" tf:"time_created,omitempty"`

	// The date and time that the routing profile was updated in the format of an RFC3339 datetime string.
	TimeUpdated *string `json:"timeUpdated,omitempty" tf:"time_updated,omitempty"`
}

type RoutingProfileParameters struct {

	// (Updatable) The OCID of the compartment in which to create the routing profile.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/identity/v1alpha1.Compartment
	// +kubebuilder:validation:Optional
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// Reference to a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDRef *v1.NamespacedReference `json:"compartmentIdRef,omitempty" tf:"-"`

	// Selector for a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDSelector *v1.NamespacedSelector `json:"compartmentIdSelector,omitempty" tf:"-"`

	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see Resource Tags.  Example: {"Operations.CostCenter": "42"}
	// +kubebuilder:validation:Optional
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// (Updatable) An optional description of the routing profile.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Updatable) A user-friendly name. Does not have to be unique, and it's changeable.
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Updatable) Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace. For more information, see Resource Tags.  Example: {"Department": "Finance"}
	// +kubebuilder:validation:Optional
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	// (Updatable) The model routing policy for the routing profile. Routing candidates are selected from the allowed models list.
	// +kubebuilder:validation:Optional
	ModelRoutingPolicy []ModelRoutingPolicyParameters `json:"modelRoutingPolicy,omitempty" tf:"model_routing_policy,omitempty"`

	// (Updatable) The cross-region routing policy for the routing profile. If this policy is not specified, only the local region is allowed.
	// +kubebuilder:validation:Optional
	RegionRoutingPolicy []RoutingProfileRegionRoutingPolicyParameters `json:"regionRoutingPolicy,omitempty" tf:"region_routing_policy,omitempty"`
}

type RoutingProfileRegionRoutingPolicyInitParameters struct {

	// (Updatable) The ordered list of regions that routing is allowed to reach. Each entry is a region identifier (for example, us-chicago-1).
	AllowedRegions []*string `json:"allowedRegions,omitempty" tf:"allowed_regions,omitempty"`
}

type RoutingProfileRegionRoutingPolicyObservation struct {

	// (Updatable) The ordered list of regions that routing is allowed to reach. Each entry is a region identifier (for example, us-chicago-1).
	AllowedRegions []*string `json:"allowedRegions,omitempty" tf:"allowed_regions,omitempty"`
}

type RoutingProfileRegionRoutingPolicyParameters struct {

	// (Updatable) The ordered list of regions that routing is allowed to reach. Each entry is a region identifier (for example, us-chicago-1).
	// +kubebuilder:validation:Optional
	AllowedRegions []*string `json:"allowedRegions,omitempty" tf:"allowed_regions,omitempty"`
}

// RoutingProfileSpec defines the desired state of RoutingProfile
type RoutingProfileSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            RoutingProfileParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RoutingProfileInitParameters `json:"initProvider,omitempty"`
}

// RoutingProfileStatus defines the observed state of RoutingProfile.
type RoutingProfileStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        RoutingProfileObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// RoutingProfile is the Schema for the RoutingProfiles API. Provides the Routing Profile resource in Oracle Cloud Infrastructure Generative AI service
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,oci}
type RoutingProfile struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.displayName) || (has(self.initProvider) && has(self.initProvider.displayName))",message="spec.forProvider.displayName is a required parameter"
	Spec   RoutingProfileSpec   `json:"spec"`
	Status RoutingProfileStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RoutingProfileList contains a list of RoutingProfiles
type RoutingProfileList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RoutingProfile `json:"items"`
}

// Repository type metadata.
var (
	RoutingProfile_Kind             = "RoutingProfile"
	RoutingProfile_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: RoutingProfile_Kind}.String()
	RoutingProfile_KindAPIVersion   = RoutingProfile_Kind + "." + CRDGroupVersion.String()
	RoutingProfile_GroupVersionKind = CRDGroupVersion.WithKind(RoutingProfile_Kind)
)

func init() {
	SchemeBuilder.Register(&RoutingProfile{}, &RoutingProfileList{})
}
