/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type CryptoAssessmentManagementCryptoPostureInitParameters struct {
}

type CryptoAssessmentManagementCryptoPostureObservation struct {
	BackupStatus *string `json:"backupStatus,omitempty" tf:"backup_status,omitempty"`

	EncryptedBackupPiecesCount *float64 `json:"encryptedBackupPiecesCount,omitempty" tf:"encrypted_backup_pieces_count,omitempty"`

	FipsModeConfigured *string `json:"fipsModeConfigured,omitempty" tf:"fips_mode_configured,omitempty"`

	FipsStatus *string `json:"fipsStatus,omitempty" tf:"fips_status,omitempty"`

	NetworkEncryption []*string `json:"networkEncryption,omitempty" tf:"network_encryption,omitempty"`

	Nne []CryptoPostureNneObservation `json:"nne,omitempty" tf:"nne,omitempty"`

	TLS []CryptoPostureTLSObservation `json:"tls,omitempty" tf:"tls,omitempty"`

	Tde []CryptoPostureTdeObservation `json:"tde,omitempty" tf:"tde,omitempty"`

	UnencryptedBackupPiecesCount *float64 `json:"unencryptedBackupPiecesCount,omitempty" tf:"unencrypted_backup_pieces_count,omitempty"`
}

type CryptoAssessmentManagementCryptoPostureParameters struct {
}

type CryptoAssessmentManagementInitParameters struct {

	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/cluster/identity/v1alpha1.Compartment
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// Reference to a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDRef *v1.Reference `json:"compartmentIdRef,omitempty" tf:"-"`

	// Selector for a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDSelector *v1.Selector `json:"compartmentIdSelector,omitempty" tf:"-"`

	CryptoAssessmentID *string `json:"cryptoAssessmentId,omitempty" tf:"crypto_assessment_id,omitempty"`

	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	IsAssessmentScheduled *bool `json:"isAssessmentScheduled,omitempty" tf:"is_assessment_scheduled,omitempty"`

	Schedule *string `json:"schedule,omitempty" tf:"schedule,omitempty"`
}

type CryptoAssessmentManagementObservation struct {
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	CryptoAssessmentID *string `json:"cryptoAssessmentId,omitempty" tf:"crypto_assessment_id,omitempty"`

	CryptoPosture []CryptoAssessmentManagementCryptoPostureObservation `json:"cryptoPosture,omitempty" tf:"crypto_posture,omitempty"`

	CryptoProvider *string `json:"cryptoProvider,omitempty" tf:"crypto_provider,omitempty"`

	DatabaseArchitecture *string `json:"databaseArchitecture,omitempty" tf:"database_architecture,omitempty"`

	DatabaseName *string `json:"databaseName,omitempty" tf:"database_name,omitempty"`

	DatabaseVersion *string `json:"databaseVersion,omitempty" tf:"database_version,omitempty"`

	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	IsAssessmentScheduled *bool `json:"isAssessmentScheduled,omitempty" tf:"is_assessment_scheduled,omitempty"`

	IssueCount *float64 `json:"issueCount,omitempty" tf:"issue_count,omitempty"`

	LifecycleDetails *string `json:"lifecycleDetails,omitempty" tf:"lifecycle_details,omitempty"`

	PostureCategory *string `json:"postureCategory,omitempty" tf:"posture_category,omitempty"`

	Schedule *string `json:"schedule,omitempty" tf:"schedule,omitempty"`

	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// +mapType=granular
	SystemTags map[string]*string `json:"systemTags,omitempty" tf:"system_tags,omitempty"`

	TargetDatabaseGroupID *string `json:"targetDatabaseGroupId,omitempty" tf:"target_database_group_id,omitempty"`

	TargetID *string `json:"targetId,omitempty" tf:"target_id,omitempty"`

	TargetType *string `json:"targetType,omitempty" tf:"target_type,omitempty"`

	TargetsWithIssuesCount *float64 `json:"targetsWithIssuesCount,omitempty" tf:"targets_with_issues_count,omitempty"`

	TimeCreated *string `json:"timeCreated,omitempty" tf:"time_created,omitempty"`

	TimeLastAssessed *string `json:"timeLastAssessed,omitempty" tf:"time_last_assessed,omitempty"`

	TimeUpdated *string `json:"timeUpdated,omitempty" tf:"time_updated,omitempty"`

	TriggeredBy *string `json:"triggeredBy,omitempty" tf:"triggered_by,omitempty"`

	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type CryptoAssessmentManagementParameters struct {

	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/cluster/identity/v1alpha1.Compartment
	// +kubebuilder:validation:Optional
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// Reference to a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDRef *v1.Reference `json:"compartmentIdRef,omitempty" tf:"-"`

	// Selector for a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDSelector *v1.Selector `json:"compartmentIdSelector,omitempty" tf:"-"`

	// +kubebuilder:validation:Optional
	CryptoAssessmentID *string `json:"cryptoAssessmentId,omitempty" tf:"crypto_assessment_id,omitempty"`

	// +kubebuilder:validation:Optional
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// +kubebuilder:validation:Optional
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	// +kubebuilder:validation:Optional
	IsAssessmentScheduled *bool `json:"isAssessmentScheduled,omitempty" tf:"is_assessment_scheduled,omitempty"`

	// +kubebuilder:validation:Optional
	Schedule *string `json:"schedule,omitempty" tf:"schedule,omitempty"`
}

type CryptoPostureNneInitParameters struct {
}

type CryptoPostureNneObservation struct {
	AreWeakOptionsAllowed *string `json:"areWeakOptionsAllowed,omitempty" tf:"are_weak_options_allowed,omitempty"`

	EncryptionConfigured []*string `json:"encryptionConfigured,omitempty" tf:"encryption_configured,omitempty"`

	FipsModeConfigured *string `json:"fipsModeConfigured,omitempty" tf:"fips_mode_configured,omitempty"`

	Integrity []*string `json:"integrity,omitempty" tf:"integrity,omitempty"`

	KeyExchange *string `json:"keyExchange,omitempty" tf:"key_exchange,omitempty"`

	QuantumReadiness *string `json:"quantumReadiness,omitempty" tf:"quantum_readiness,omitempty"`

	ServerEncryption *string `json:"serverEncryption,omitempty" tf:"server_encryption,omitempty"`

	ServerIntegrity []*string `json:"serverIntegrity,omitempty" tf:"server_integrity,omitempty"`

	Status *string `json:"status,omitempty" tf:"status,omitempty"`
}

type CryptoPostureNneParameters struct {
}

type CryptoPostureTLSInitParameters struct {
}

type CryptoPostureTLSObservation struct {
	AreWeakCipherSuitesAllowed *string `json:"areWeakCipherSuitesAllowed,omitempty" tf:"are_weak_cipher_suites_allowed,omitempty"`

	CipherSuitesConfigured []*string `json:"cipherSuitesConfigured,omitempty" tf:"cipher_suites_configured,omitempty"`

	FipsModeConfigured *string `json:"fipsModeConfigured,omitempty" tf:"fips_mode_configured,omitempty"`

	IsMtlsConfigured *string `json:"isMtlsConfigured,omitempty" tf:"is_mtls_configured,omitempty"`

	QuantumReadiness *string `json:"quantumReadiness,omitempty" tf:"quantum_readiness,omitempty"`

	RevocationMode *string `json:"revocationMode,omitempty" tf:"revocation_mode,omitempty"`

	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	Versions []*string `json:"versions,omitempty" tf:"versions,omitempty"`

	WalletLocation *string `json:"walletLocation,omitempty" tf:"wallet_location,omitempty"`
}

type CryptoPostureTLSParameters struct {
}

type CryptoPostureTdeInitParameters struct {
}

type CryptoPostureTdeObservation struct {
	DBCredentialsEncryptionObserved *string `json:"dbCredentialsEncryptionObserved,omitempty" tf:"db_credentials_encryption_observed,omitempty"`

	EncryptedTablespacesCount *float64 `json:"encryptedTablespacesCount,omitempty" tf:"encrypted_tablespaces_count,omitempty"`

	EncryptionConfigured []*string `json:"encryptionConfigured,omitempty" tf:"encryption_configured,omitempty"`

	FipsModeConfigured *string `json:"fipsModeConfigured,omitempty" tf:"fips_mode_configured,omitempty"`

	IntegrityConfigured []*string `json:"integrityConfigured,omitempty" tf:"integrity_configured,omitempty"`

	KeyCacheStatus *string `json:"keyCacheStatus,omitempty" tf:"key_cache_status,omitempty"`

	KeyStoreType *string `json:"keyStoreType,omitempty" tf:"key_store_type,omitempty"`

	MasterKeyEncryptionAlgorithm *string `json:"masterKeyEncryptionAlgorithm,omitempty" tf:"master_key_encryption_algorithm,omitempty"`

	MasterKeyID *string `json:"masterKeyId,omitempty" tf:"master_key_id,omitempty"`

	QuantumReadiness *string `json:"quantumReadiness,omitempty" tf:"quantum_readiness,omitempty"`

	RedoEncryptionObserved *string `json:"redoEncryptionObserved,omitempty" tf:"redo_encryption_observed,omitempty"`

	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	TimeMasterKeyLastRotation *string `json:"timeMasterKeyLastRotation,omitempty" tf:"time_master_key_last_rotation,omitempty"`

	UnencryptedTablespacesCount *float64 `json:"unencryptedTablespacesCount,omitempty" tf:"unencrypted_tablespaces_count,omitempty"`

	WalletLocation *string `json:"walletLocation,omitempty" tf:"wallet_location,omitempty"`
}

type CryptoPostureTdeParameters struct {
}

// CryptoAssessmentManagementSpec defines the desired state of CryptoAssessmentManagement
type CryptoAssessmentManagementSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     CryptoAssessmentManagementParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider CryptoAssessmentManagementInitParameters `json:"initProvider,omitempty"`
}

// CryptoAssessmentManagementStatus defines the observed state of CryptoAssessmentManagement.
type CryptoAssessmentManagementStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        CryptoAssessmentManagementObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// CryptoAssessmentManagement is the Schema for the CryptoAssessmentManagements API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,oci}
type CryptoAssessmentManagement struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.cryptoAssessmentId) || (has(self.initProvider) && has(self.initProvider.cryptoAssessmentId))",message="spec.forProvider.cryptoAssessmentId is a required parameter"
	Spec   CryptoAssessmentManagementSpec   `json:"spec"`
	Status CryptoAssessmentManagementStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CryptoAssessmentManagementList contains a list of CryptoAssessmentManagements
type CryptoAssessmentManagementList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []CryptoAssessmentManagement `json:"items"`
}

// Repository type metadata.
var (
	CryptoAssessmentManagement_Kind             = "CryptoAssessmentManagement"
	CryptoAssessmentManagement_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: CryptoAssessmentManagement_Kind}.String()
	CryptoAssessmentManagement_KindAPIVersion   = CryptoAssessmentManagement_Kind + "." + CRDGroupVersion.String()
	CryptoAssessmentManagement_GroupVersionKind = CRDGroupVersion.WithKind(CryptoAssessmentManagement_Kind)
)

func init() {
	SchemeBuilder.Register(&CryptoAssessmentManagement{}, &CryptoAssessmentManagementList{})
}
